apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/agents/realization/deployment.yaml
  - ../../../../base/agents/realization/hpa.yaml
commonLabels:
  app.kubernetes.io/part-of: valueos-agents
  valueos.io/agent-name: realization
namespace: valueos-agents
