/** @type {import('tailwindcss').Config} */
const config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          '"Roboto Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      colors: {
        "vc-surface-1": "hsl(var(--vc-surface-1))",
        "vc-surface-2": "hsl(var(--vc-surface-2))",
        "vc-surface-3": "hsl(var(--vc-surface-3))",
        "vc-accent-teal-500": "hsl(var(--vc-accent-teal-500))",
        "vc-accent-teal-400": "hsl(var(--vc-accent-teal-400))",
        "vc-accent-grey-500": "hsl(var(--vc-accent-grey-500))",
        "vc-border-default": "hsl(var(--vc-border-default))",
        "vc-border-strong": "hsl(var(--vc-border-strong))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        success: "hsl(var(--status-success))",
        "success-foreground": "hsl(var(--foreground))",
        warning: "hsl(var(--status-warning))",
        "warning-foreground": "hsl(var(--foreground))",
        error: "hsl(var(--status-error))",
        "error-foreground": "hsl(var(--foreground))",
        info: "hsl(var(--status-info))",
        "info-foreground": "hsl(var(--foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        sidebar: {
          background: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      spacing: {
        "vc-1": "var(--spacing-1)",
        "vc-2": "var(--spacing-2)",
        "vc-3": "var(--spacing-3)",
        "vc-4": "var(--spacing-4)",
        "vc-6": "var(--spacing-6)",
        "vc-8": "var(--spacing-8)",
      },
      fontSize: {
        xs: "var(--font-xs)",
        sm: "var(--font-sm)",
        base: "var(--font-base)",
        "3xl": "var(--font-3xl)",
        "5xl": "var(--font-5xl)",
        "6xl": "var(--font-6xl)",
      },
      letterSpacing: {
        "vc-hero": "var(--font-tracking-hero)",
        "vc-micro": "var(--font-tracking-micro)",
      },
      borderRadius: {
        lg: "var(--vc-radius-card)",
        md: "var(--vc-radius-card)",
        sm: "calc(var(--vc-radius-card) - 0.25rem)",
        xl: "var(--vc-radius-modal)",
        "vc-card": "var(--vc-radius-card)",
        "vc-modal": "var(--vc-radius-modal)",
        "vc-pill": "9999px",
      },
      boxShadow: {
        "vc-glow-teal": "var(--vc-glow-teal)",
        "glow-teal": "0 0 15px rgba(16, 185, 129, 0.4)",
        "glow-teal-lg": "0 0 25px rgba(16, 185, 129, 0.6)",
        "glow-green": "0 0 10px rgba(16, 185, 129, 0.5)",
        "inner-glow": "inset 0 1px 0 0 rgba(255, 255, 255, 0.05)",
      },
      backgroundImage: {
        "gradient-value": "linear-gradient(to right, #10B981, #34D399)",
        "gradient-radial": "radial-gradient(circle, var(--tw-gradient-stops))",
        "canvas-grid":
          "radial-gradient(rgba(255,255,255,0.02) 1px, transparent 1px)",
      },
    },
  },
  plugins: [],
};

export default config;
