module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        card: "hsl(var(--card))",
        popover: "hsl(var(--popover))",
        foreground: "hsl(var(--foreground))",
        "card-foreground": "hsl(var(--card-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        border: "hsl(var(--border))",
        ring: "hsl(var(--ring))",
        success: "hsl(var(--status-success))",
        destructive: "hsl(var(--status-error))",
        warning: "hsl(var(--status-warning))",
        info: "hsl(var(--status-info))",
      },
      spacing: {
        "vc-1": "0.5rem",
        "vc-2": "1rem",
        "vc-3": "1.5rem",
        "vc-4": "2rem",
        "vc-6": "3rem",
        "vc-8": "4rem",
      },
      borderRadius: {
        "vc-md": "0.5rem",
        "vc-xl": "1rem",
      },
      fontFamily: {
        sans: [
          "Inter",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Roboto Mono",
          "Courier New",
          "monospace",
        ],
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        "3xl": "1.875rem",
        "5xl": "3rem",
        "6xl": "3.75rem",
      },
    },
  },
  plugins: [],
};
