import { Counter, Histogram, metrics } from "@opentelemetry/api";

import { logger } from "../../../lib/logger.js";
import { AgentType } from "../../agent-types.js";

type TelemetrySeverity = "debug" | "info" | "warning" | "error";

type TelemetryEvent = {
  type: string;
  agentType: AgentType;
  organizationId?: string;
  sessionId?: string;
  userId?: string;
  data?: Record<string, unknown>;
  severity?: TelemetrySeverity;
};

type MetricOutcome = "success" | "failure" | "timeout" | "fallback" | "retry" | "unknown";

type MetricAttributes = Record<string, string>;

const AGENT_TYPE_ALLOWLIST = new Set<string>([...AgentType, "system", "unknown"]);

const EVENT_TYPE_ALLOWLIST = new Set<string>([
  "agent_execution_complete",
  "agent_execution_error",
  "agent_execution_timeout",
  "agent_retry_success",
  "agent_retry_failure",
  "agent_fallback_success",
  "agent_fallback_parallel_success",
  "agent_security_violation",
  "agent_fabric_global_rate_limit",
]);

const SEVERITY_ALLOWLIST = new Set<TelemetrySeverity | "unknown">([
  "debug",
  "info",
  "warning",
  "error",
  "unknown",
]);

const OUTCOME_ALLOWLIST = new Set<MetricOutcome>([
  "success",
  "failure",
  "timeout",
  "fallback",
  "retry",
  "unknown",
]);

export class AgentTelemetryService {
  private static readonly TENANT_BUCKET_COUNT = 64;
  private meter = metrics.getMeter("agent-fabric");
  private executionSuccessCounter: Counter = this.meter.createCounter(
    "agent_fabric_execution_success_total",
    {
      description: "Total number of successful agent executions",
      unit: "{execution}",
    }
  );
  private executionFailureCounter: Counter = this.meter.createCounter(
    "agent_fabric_execution_failure_total",
    {
      description: "Total number of failed agent executions",
      unit: "{execution}",
    }
  );
  private executionDurationHistogram: Histogram = this.meter.createHistogram(
    "agent_fabric_execution_duration_seconds",
    {
      description: "Agent execution duration in seconds",
      unit: "s",
    }
  );
  private securityEventsCounter: Counter = this.meter.createCounter(
    "agent_fabric_security_events_total",
    {
      description: "Total security-related events emitted by agent fabric",
      unit: "{event}",
    }
  );
  private valueGeneratedCounter: Counter = this.meter.createCounter(
    "agent_fabric_value_generated_usd_total",
    {
      description: "Total business value generated by agent executions in USD",
      unit: "USD",
    }
  );
  private costCounter: Counter = this.meter.createCounter("agent_fabric_cost_usd_total", {
    description: "Total USD cost of agent executions",
    unit: "USD",
  });
  private tokenUsageCounter: Counter = this.meter.createCounter("agent_fabric_token_usage_total", {
    description: "Total tokens consumed by agent executions",
    unit: "{token}",
  });

  recordTelemetryEvent(event: TelemetryEvent): void {
    logger.debug("Agent telemetry event", {
      type: event.type,
      agentType: event.agentType,
      severity: event.severity,
      data: event.data,
    });

    this.recordMetrics(event);
  }

  private recordMetrics(event: TelemetryEvent): void {
    const attributes = this.buildMetricAttributes(event);
    const durationSeconds = this.getDurationSeconds(event.data);
    if (durationSeconds !== undefined) {
      this.executionDurationHistogram.record(durationSeconds, attributes);
    }

    const successEventTypes = new Set([
      "agent_execution_complete",
      "agent_retry_success",
      "agent_fallback_success",
      "agent_fallback_parallel_success",
    ]);
    const failureEventTypes = new Set([
      "agent_execution_error",
      "agent_execution_timeout",
      "agent_retry_failure",
    ]);

    if (successEventTypes.has(event.type)) {
      this.executionSuccessCounter.add(1, attributes);
    }

    if (failureEventTypes.has(event.type)) {
      this.executionFailureCounter.add(1, attributes);
    }

    if (event.type.includes("security") || event.type === "agent_security_violation") {
      this.securityEventsCounter.add(1, attributes);
    }

    const tokenUsage = this.getNumber(event.data, ["tokenUsage", "tokens", "tokenCount"]);
    if (tokenUsage !== undefined) {
      this.tokenUsageCounter.add(tokenUsage, attributes);
    }

    const costUsd = this.getNumber(event.data, ["costUsd", "cost", "costUSD"]);
    if (costUsd !== undefined) {
      this.costCounter.add(costUsd, attributes);
    }

    const valueGeneratedUsd = this.getNumber(event.data, [
      "valueGeneratedUsd",
      "valueUsd",
      "valueGenerated",
    ]);
    if (valueGeneratedUsd !== undefined) {
      this.valueGeneratedCounter.add(valueGeneratedUsd, attributes);
    }
  }

  private buildMetricAttributes(event: TelemetryEvent): MetricAttributes {
    const eventType = EVENT_TYPE_ALLOWLIST.has(event.type) ? event.type : "other";
    const agentType = AGENT_TYPE_ALLOWLIST.has(event.agentType) ? event.agentType : "unknown";
    const severity = SEVERITY_ALLOWLIST.has(event.severity ?? "unknown")
      ? (event.severity ?? "unknown")
      : "unknown";
    const outcome = this.getOutcome(eventType);

    const attributes: MetricAttributes = {
      agent_type: agentType,
      event_type: eventType,
      severity,
      outcome,
    };

    const organizationId = this.getOrganizationId(event);
    if (organizationId) {
      if (event.data?.allowOrgIdDimension === true) {
        attributes.organization_id = this.sanitizeOrganizationId(organizationId);
      } else {
        attributes.tenant_bucket = this.toTenantBucket(organizationId);
      }
    }

    return attributes;
  }

  private getOutcome(eventType: string): MetricOutcome {
    if (eventType.includes("timeout")) {
      return "timeout";
    }
    if (eventType.includes("failure") || eventType.includes("error")) {
      return "failure";
    }
    if (eventType.includes("fallback")) {
      return "fallback";
    }
    if (eventType.includes("retry")) {
      return "retry";
    }
    if (eventType.includes("complete") || eventType.includes("success")) {
      return "success";
    }
    return OUTCOME_ALLOWLIST.has("unknown") ? "unknown" : "failure";
  }

  private getOrganizationId(event: TelemetryEvent): string | undefined {
    if (typeof event.organizationId === "string" && event.organizationId.length > 0) {
      return event.organizationId;
    }

    const metadataOrganizationId = event.data?.organizationId;
    if (typeof metadataOrganizationId === "string" && metadataOrganizationId.length > 0) {
      return metadataOrganizationId;
    }

    const metadataTenantId = event.data?.tenantId;
    if (typeof metadataTenantId === "string" && metadataTenantId.length > 0) {
      return metadataTenantId;
    }

    return undefined;
  }

  private sanitizeOrganizationId(organizationId: string): string {
    return /^[a-zA-Z0-9_-]{1,64}$/.test(organizationId) ? organizationId : "redacted";
  }

  private toTenantBucket(organizationId: string): string {
    let hash = 0;
    for (let i = 0; i < organizationId.length; i++) {
      hash = (hash * 31 + organizationId.charCodeAt(i)) | 0;
    }

    const bucket = Math.abs(hash) % AgentTelemetryService.TENANT_BUCKET_COUNT;
    return `tb_${bucket.toString().padStart(2, "0")}`;
  }

  private getDurationSeconds(data?: Record<string, unknown>): number | undefined {
    const durationSeconds = this.getNumber(data, [
      "durationSeconds",
      "executionDurationSeconds",
    ]);
    if (durationSeconds !== undefined) {
      return durationSeconds;
    }

    const durationMs = this.getNumber(data, ["durationMs", "executionDurationMs", "duration"]);
    if (durationMs === undefined) {
      return undefined;
    }

    return durationMs / 1000;
  }

  private getNumber(
    data: Record<string, unknown> | undefined,
    keys: string[]
  ): number | undefined {
    if (!data) {
      return undefined;
    }

    for (const key of keys) {
      const value = data[key];
      if (typeof value === "number" && Number.isFinite(value)) {
        return value;
      }
    }

    return undefined;
  }
}

export const agentTelemetryService = new AgentTelemetryService();
