import { metrics, Counter, Histogram } from "@opentelemetry/api";
import { AgentType } from "../../agent-types.js";
import { logger } from "../../../lib/logger.js";

type TelemetrySeverity = "debug" | "info" | "warning" | "error";

type TelemetryEvent = {
  type: string;
  agentType: AgentType;
  sessionId?: string;
  userId?: string;
  data?: Record<string, unknown>;
  severity?: TelemetrySeverity;
};

class AgentTelemetryService {
  private meter = metrics.getMeter("agent-fabric");
  private executionSuccessCounter: Counter = this.meter.createCounter(
    "agent_fabric_execution_success_total",
    {
      description: "Total number of successful agent executions",
      unit: "{execution}",
    }
  );
  private executionFailureCounter: Counter = this.meter.createCounter(
    "agent_fabric_execution_failure_total",
    {
      description: "Total number of failed agent executions",
      unit: "{execution}",
    }
  );
  private executionDurationHistogram: Histogram = this.meter.createHistogram(
    "agent_fabric_execution_duration_seconds",
    {
      description: "Agent execution duration in seconds",
      unit: "s",
    }
  );
  private securityEventsCounter: Counter = this.meter.createCounter(
    "agent_fabric_security_events_total",
    {
      description: "Total security-related events emitted by agent fabric",
      unit: "{event}",
    }
  );
  private valueGeneratedCounter: Counter = this.meter.createCounter(
    "agent_fabric_value_generated_usd_total",
    {
      description: "Total business value generated by agent executions in USD",
      unit: "USD",
    }
  );
  private costCounter: Counter = this.meter.createCounter("agent_fabric_cost_usd_total", {
    description: "Total USD cost of agent executions",
    unit: "USD",
  });
  private tokenUsageCounter: Counter = this.meter.createCounter("agent_fabric_token_usage_total", {
    description: "Total tokens consumed by agent executions",
    unit: "{token}",
  });

  recordTelemetryEvent(event: TelemetryEvent): void {
    logger.debug("Agent telemetry event", {
      type: event.type,
      agentType: event.agentType,
      severity: event.severity,
      data: event.data,
    });

    this.recordMetrics(event);
  }

  private recordMetrics(event: TelemetryEvent): void {
    const durationSeconds = this.getDurationSeconds(event.data);
    if (durationSeconds !== undefined) {
      this.executionDurationHistogram.record(durationSeconds);
    }

    const successEventTypes = new Set([
      "agent_execution_complete",
      "agent_retry_success",
      "agent_fallback_success",
      "agent_fallback_parallel_success",
    ]);
    const failureEventTypes = new Set([
      "agent_execution_error",
      "agent_execution_timeout",
      "agent_retry_failure",
    ]);

    if (successEventTypes.has(event.type)) {
      this.executionSuccessCounter.add(1);
    }

    if (failureEventTypes.has(event.type)) {
      this.executionFailureCounter.add(1);
    }

    if (event.type.includes("security") || event.type === "agent_security_violation") {
      this.securityEventsCounter.add(1);
    }

    const tokenUsage = this.getNumber(event.data, ["tokenUsage", "tokens", "tokenCount"]);
    if (tokenUsage !== undefined) {
      this.tokenUsageCounter.add(tokenUsage);
    }

    const costUsd = this.getNumber(event.data, ["costUsd", "cost", "costUSD"]);
    if (costUsd !== undefined) {
      this.costCounter.add(costUsd);
    }

    const valueGeneratedUsd = this.getNumber(event.data, [
      "valueGeneratedUsd",
      "valueUsd",
      "valueGenerated",
    ]);
    if (valueGeneratedUsd !== undefined) {
      this.valueGeneratedCounter.add(valueGeneratedUsd);
    }
  }

  private getDurationSeconds(data?: Record<string, unknown>): number | undefined {
    const durationSeconds = this.getNumber(data, [
      "durationSeconds",
      "executionDurationSeconds",
    ]);
    if (durationSeconds !== undefined) {
      return durationSeconds;
    }

    const durationMs = this.getNumber(data, ["durationMs", "executionDurationMs", "duration"]);
    if (durationMs === undefined) {
      return undefined;
    }

    return durationMs / 1000;
  }

  private getNumber(
    data: Record<string, unknown> | undefined,
    keys: string[]
  ): number | undefined {
    if (!data) {
      return undefined;
    }

    for (const key of keys) {
      const value = data[key];
      if (typeof value === "number" && Number.isFinite(value)) {
        return value;
      }
    }

    return undefined;
  }
}

export const agentTelemetryService = new AgentTelemetryService();
