-- Deterministic inventory of tenant-scoped tables and required policy predicates.
-- access_model:
--   tenant_column => policies must scope by tenant_id/organization_id
--   membership    => policies may scope via tenant membership joins/helpers

CREATE TEMP TABLE tenant_scope_inventory (
  schema_name text NOT NULL,
  table_name text NOT NULL,
  access_model text NOT NULL CHECK (access_model IN ('tenant_column', 'membership')),
  required_policy_regex text NOT NULL,
  required_policy_description text NOT NULL,
  PRIMARY KEY (schema_name, table_name)
) ON COMMIT DROP;

INSERT INTO tenant_scope_inventory (
  schema_name,
  table_name,
  access_model,
  required_policy_regex,
  required_policy_description
)
VALUES
  ('public', 'ab_tests', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'academy_certifications', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'academy_progress', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_accuracy_metrics', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_activities', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_audit_log', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_memory', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_metrics', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_ontologies', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_predictions', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_retraining_queue', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agents', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_sessions', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'agent_tools', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'approval_requests', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'approvals', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'approver_roles', 'membership', '(user_tenants|get_user_tenant_ids|is_organization_member|auth\.uid\(\))', 'Policy predicates must scope rows through tenant membership checks.'),
  ('public', 'assumptions', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'audit_log_access', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'audit_logs', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'audit_logs_archive', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'automated_check_results', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'automated_responses', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'backup_logs', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'billing_customers', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'billing_approval_policies', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'billing_approval_requests', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'business_cases', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'canvas_components', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'company_profiles', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'compensation_queue', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'compliance_evidence', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'compliance_reports', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'component_history', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'component_relationships', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'confidence_violations', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'contextual_triggers', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'cost_alerts', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'device_trust_history', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'evaluation_runs', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'expansion_results', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'entitlement_snapshots', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'feature_flag_evaluations', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'feature_flags', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'feedback_loops', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'financial_models', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'golden_examples', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'integrity_results', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'invoices', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'kpi_hypotheses', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'llm_calls', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'llm_job_results', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'llm_usage', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'message_bus', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'opportunity_results', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'policy_rules', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'prompt_executions', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'prompt_versions', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'rate_limit_violations', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'realization_results', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'resource_artifacts', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'roles', 'membership', '(user_tenants|get_user_tenant_ids|is_organization_member|auth\.uid\(\))', 'Policy predicates must scope rows through tenant membership checks.'),
  ('public', 'secret_audit_logs', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'security_audit_log', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'security_events', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'security_incidents', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'security_metrics', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'security_policies', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'semantic_memory', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'subscription_items', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'subscriptions', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'system_metrics', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'target_results', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'task_queue', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'tenant_integrations', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'tenants', 'membership', '(user_tenants|get_user_tenant_ids|is_organization_member|auth\.uid\(\))', 'Policy predicates must scope rows through tenant membership checks.'),
  ('public', 'usage_aggregates', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'usage_alerts', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'usage_events', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'usage_policies', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'usage_quotas', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'user_behavior_analysis', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'user_roles', 'membership', '(user_tenants|get_user_tenant_ids|is_organization_member|auth\.uid\(\))', 'Policy predicates must scope rows through tenant membership checks.'),
  ('public', 'user_sessions', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'user_tenants', 'membership', '(user_tenants|get_user_tenant_ids|is_organization_member|auth\.uid\(\))', 'Policy predicates must scope rows through tenant membership checks.'),
  ('public', 'value_cases', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'value_ledger', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'value_maps', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'value_prediction_accuracy', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'value_tree_links', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'value_tree_nodes', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'value_trees', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'workflow_executions', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'workflow_states', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.'),
  ('public', 'workflows', 'tenant_column', '(tenant_id|organization_id)', 'Policy predicates must scope rows by tenant_id/organization_id.');
