/**
 * Artifacts API Routes
 * 
 * CRUD endpoints for artifact persistence.
 * Artifacts are generated by the agent and stored per value case.
 */

import { Router, Request, Response, NextFunction } from 'express';
import { z, ZodError } from 'zod';
import { v4 as uuidv4 } from 'uuid';
import { tenantContextMiddleware } from '../../middleware/tenantContext.js'
import { tenantDbContextMiddleware } from '../../middleware/tenantDbContext.js'
import { 
  CreateArtifactSchema,
  UpdateArtifactSchema,
  ListArtifactsQuerySchema,
  BatchCreateArtifactsSchema,
  ApiErrorResponse,
} from './types';
import { 
  getArtifactsRepository,
  NotFoundError,
  DatabaseError,
} from './repository';
// Note: Auth middleware imports may need adjustment based on your setup
// import { requireAuth, requireRole } from '../../middleware/auth';
// import { createRateLimiter, RateLimitTier } from '../../middleware/rateLimiter';

// Placeholder middleware until auth is wired up
const requireAuth = (_req: Request, _res: Response, next: NextFunction) => next();
const requireRole = (_roles: string[]) => (_req: Request, _res: Response, next: NextFunction) => next();
const standardLimiter = (_req: Request, _res: Response, next: NextFunction) => next();
const strictLimiter = (_req: Request, _res: Response, next: NextFunction) => next();

// Simple logger for now
const logger = {
  info: (msg: string, data?: Record<string, unknown>) => console.log(`[INFO] ${msg}`, data || ''),
  error: (msg: string, data?: Record<string, unknown>) => console.error(`[ERROR] ${msg}`, data || ''),
  warn: (msg: string, data?: Record<string, unknown>) => console.warn(`[WARN] ${msg}`, data || ''),
};

// ============================================================================
// Types
// ============================================================================

interface AuthenticatedRequest extends Request {
  user?: { id: string; role?: string };
  tenantId?: string;
  correlationId?: string;
}

// ============================================================================
// Router Setup
// ============================================================================

const router = Router();

// ============================================================================
// Middleware
// ============================================================================

/**
 * Add correlation ID to request
 */
function correlationId(req: Request, _res: Response, next: NextFunction): void {
  (req as AuthenticatedRequest).correlationId = 
    (req.headers['x-correlation-id'] as string) || `req-${uuidv4()}`;
  next();
}

/**
 * Request logging middleware
 */
function requestLogger(req: Request, res: Response, next: NextFunction): void {
  const startTime = Date.now();
  const authReq = req as AuthenticatedRequest;

  res.on('finish', () => {
    const latencyMs = Date.now() - startTime;
    logger.info('Artifacts API request completed', {
      requestId: authReq.correlationId,
      method: req.method,
      path: req.path,
      status: res.statusCode,
      latencyMs,
      tenantId: authReq.tenantId,
      userId: authReq.user?.id,
    });
  });

  next();
}

/**
 * Validate request body against schema
 */
function validateBody<T>(schema: z.ZodSchema<T>) {
  return (req: Request, res: Response, next: NextFunction): void => {
    try {
      req.body = schema.parse(req.body);
      next();
    } catch (err) {
      if (err instanceof ZodError) {
        const errors = err.errors.map(e => ({
          field: e.path.join('.'),
          message: e.message,
        }));

        res.status(400).json({
          error: 'VALIDATION_ERROR',
          message: 'Invalid request body',
          details: { errors },
          requestId: (req as AuthenticatedRequest).correlationId,
        } satisfies ApiErrorResponse);
        return;
      }
      next(err);
    }
  };
}

/**
 * Validate query params against schema
 */
function validateQuery<T>(schema: z.ZodSchema<T>) {
  return (req: Request, res: Response, next: NextFunction): void => {
    try {
      req.query = schema.parse(req.query) as unknown as typeof req.query;
      next();
    } catch (err) {
      if (err instanceof ZodError) {
        const errors = err.errors.map(e => ({
          field: e.path.join('.'),
          message: e.message,
        }));

        res.status(400).json({
          error: 'VALIDATION_ERROR',
          message: 'Invalid query parameters',
          details: { errors },
          requestId: (req as AuthenticatedRequest).correlationId,
        } satisfies ApiErrorResponse);
        return;
      }
      next(err);
    }
  };
}

/**
 * Validate UUID path parameter
 */
function validateUuidParam(paramName: string) {
  return (req: Request, res: Response, next: NextFunction): void => {
    const value = req.params[paramName];
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

    if (!value || !uuidRegex.test(value)) {
      res.status(400).json({
        error: 'VALIDATION_ERROR',
        message: `Invalid ${paramName}: must be a valid UUID`,
        requestId: (req as AuthenticatedRequest).correlationId,
      } satisfies ApiErrorResponse);
      return;
    }
    next();
  };
}

// ============================================================================
// Error Handler
// ============================================================================

/**
 * Map repository errors to HTTP responses
 */
function handleError(
  err: unknown,
  req: Request,
  res: Response,
  _next: NextFunction
): void {
  const authReq = req as AuthenticatedRequest;
  const requestId = authReq.correlationId;

  if (err instanceof NotFoundError) {
    res.status(404).json({
      error: 'NOT_FOUND',
      message: err.message,
      requestId,
    } satisfies ApiErrorResponse);
    return;
  }

  if (err instanceof DatabaseError) {
    logger.error('Database error in artifacts API', {
      requestId,
      error: err.message,
      code: err.code,
    });

    res.status(503).json({
      error: 'SERVICE_UNAVAILABLE',
      message: 'Database temporarily unavailable. Please retry.',
      requestId,
    } satisfies ApiErrorResponse);
    return;
  }

  logger.error('Unexpected error in artifacts API', {
    requestId,
    error: err instanceof Error ? err.message : 'Unknown error',
    path: req.path,
    method: req.method,
  });

  res.status(500).json({
    error: 'INTERNAL_ERROR',
    message: 'An unexpected error occurred',
    requestId,
  } satisfies ApiErrorResponse);
}

// ============================================================================
// Route Handlers
// ============================================================================

/**
 * POST /api/v1/artifacts
 * Create a new artifact
 */
async function createArtifact(req: Request, res: Response, next: NextFunction): Promise<void> {
  const authReq = req as AuthenticatedRequest;

  try {
    const repository = getArtifactsRepository();
    const artifact = await repository.create(authReq.tenantId!, req.body);

    res.status(201).json({
      data: artifact,
      requestId: authReq.correlationId,
    });
  } catch (err) {
    next(err);
  }
}

/**
 * POST /api/v1/artifacts/batch
 * Create multiple artifacts at once
 */
async function createArtifactsBatch(req: Request, res: Response, next: NextFunction): Promise<void> {
  const authReq = req as AuthenticatedRequest;

  try {
    const repository = getArtifactsRepository();
    const { valueCaseId, artifacts } = req.body;
    const created = await repository.createBatch(authReq.tenantId!, valueCaseId, artifacts);

    res.status(201).json({
      data: created,
      requestId: authReq.correlationId,
    });
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/v1/artifacts
 * List artifacts with pagination
 */
async function listArtifacts(req: Request, res: Response, next: NextFunction): Promise<void> {
  const authReq = req as AuthenticatedRequest;

  try {
    const repository = getArtifactsRepository();
    const result = await repository.list(authReq.tenantId!, req.query as any);

    res.status(200).json({
      ...result,
      requestId: authReq.correlationId,
    });
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/v1/artifacts/:artifactId
 * Get a single artifact
 */
async function getArtifact(req: Request, res: Response, next: NextFunction): Promise<void> {
  const authReq = req as AuthenticatedRequest;
  const { artifactId } = req.params;

  try {
    const repository = getArtifactsRepository();
    const artifact = await repository.getById(authReq.tenantId!, artifactId);

    res.status(200).json({
      data: artifact,
      requestId: authReq.correlationId,
    });
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/v1/artifacts/case/:caseId
 * Get all artifacts for a value case
 */
async function getArtifactsByCase(req: Request, res: Response, next: NextFunction): Promise<void> {
  const authReq = req as AuthenticatedRequest;
  const { caseId } = req.params;

  try {
    const repository = getArtifactsRepository();
    const artifacts = await repository.getByValueCase(authReq.tenantId!, caseId);

    res.status(200).json({
      data: artifacts,
      requestId: authReq.correlationId,
    });
  } catch (err) {
    next(err);
  }
}

/**
 * PATCH /api/v1/artifacts/:artifactId
 * Update an artifact
 */
async function updateArtifact(req: Request, res: Response, next: NextFunction): Promise<void> {
  const authReq = req as AuthenticatedRequest;
  const { artifactId } = req.params;

  try {
    const repository = getArtifactsRepository();
    const artifact = await repository.update(authReq.tenantId!, artifactId, req.body);

    res.status(200).json({
      data: artifact,
      requestId: authReq.correlationId,
    });
  } catch (err) {
    next(err);
  }
}

/**
 * DELETE /api/v1/artifacts/:artifactId
 * Delete an artifact
 */
async function deleteArtifact(req: Request, res: Response, next: NextFunction): Promise<void> {
  const authReq = req as AuthenticatedRequest;
  const { artifactId } = req.params;

  try {
    const repository = getArtifactsRepository();
    await repository.delete(authReq.tenantId!, artifactId);

    res.status(204).send();
  } catch (err) {
    next(err);
  }
}

// ============================================================================
// Route Definitions
// ============================================================================

// Apply common middleware
router.use(correlationId);
router.use(requestLogger);

// All routes require authentication
router.use(requireAuth);
router.use(tenantContextMiddleware(), tenantDbContextMiddleware());

// POST /artifacts - Create single
router.post(
  '/',
  strictLimiter,
  requireRole(['admin', 'member']),
  validateBody(CreateArtifactSchema),
  createArtifact
);

// POST /artifacts/batch - Create multiple
router.post(
  '/batch',
  strictLimiter,
  requireRole(['admin', 'member']),
  validateBody(BatchCreateArtifactsSchema),
  createArtifactsBatch
);

// GET /artifacts - List
router.get(
  '/',
  standardLimiter,
  requireRole(['admin', 'member', 'viewer']),
  validateQuery(ListArtifactsQuerySchema),
  listArtifacts
);

// GET /artifacts/case/:caseId - Get by case
router.get(
  '/case/:caseId',
  standardLimiter,
  requireRole(['admin', 'member', 'viewer']),
  validateUuidParam('caseId'),
  getArtifactsByCase
);

// GET /artifacts/:artifactId - Get one
router.get(
  '/:artifactId',
  standardLimiter,
  requireRole(['admin', 'member', 'viewer']),
  validateUuidParam('artifactId'),
  getArtifact
);

// PATCH /artifacts/:artifactId - Update
router.patch(
  '/:artifactId',
  standardLimiter,
  requireRole(['admin', 'member']),
  validateUuidParam('artifactId'),
  validateBody(UpdateArtifactSchema),
  updateArtifact
);

// DELETE /artifacts/:artifactId - Delete
router.delete(
  '/:artifactId',
  strictLimiter,
  requireRole(['admin']),
  validateUuidParam('artifactId'),
  deleteArtifact
);

// Error handler
router.use(handleError);

export default router;
export { router as artifactsRouter };
