/**
 * Generated by `pnpm db:types` (or `pnpm db:types:remote`).
 * DO NOT HAND EDIT.
 */

// This placeholder is kept in-repo so type exports remain resolvable before generation.
// Regenerate using the command above to sync with the latest database schema.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = Record<string, never>;
