/**
 * BusinessCase — canonical domain object
 *
 * The customer-facing artifact that packages validated hypotheses, financial
 * models, and evidence into a presentable business case document.
 * Generated by ArtifactComposer (Sprint 4 target).
 *
 * Consolidates:
 * - BusinessCase interface (packages/backend/src/services/PersistenceService.ts)
 * - Value case concept (packages/backend/src/api/valueCases/types.ts)
 *
 * Sprint 3: First-class domain definition.
 */

import { z } from "zod";

export const BusinessCaseStatusSchema = z.enum([
  "draft",
  "in_review",
  "approved",
  "presented",
  "archived",
]);
export type BusinessCaseStatus = z.infer<typeof BusinessCaseStatusSchema>;

export const FinancialSummarySchema = z.object({
  /** Total value range across all validated hypotheses. */
  total_value_low_usd: z.number().nonnegative(),
  total_value_high_usd: z.number().nonnegative(),

  /** Payback period in months. */
  payback_months: z.number().positive().nullable().optional(),

  /** 3-year ROI as a multiplier (e.g. 3.2 = 320% ROI). */
  roi_3yr: z.number().nullable().optional(),

  /** IRR as a decimal (e.g. 0.45 = 45%). */
  irr: z.number().nullable().optional(),

  /** Currency code (ISO 4217). */
  currency: z.string().length(3).default("USD"),
});
export type FinancialSummary = z.infer<typeof FinancialSummarySchema>;

export const BusinessCaseSchema = z.object({
  /** Stable internal identifier (UUID). */
  id: z.string().uuid(),

  /** Tenant that owns this record. All queries must filter on this. */
  organization_id: z.string().uuid(),

  /** The opportunity this business case belongs to. */
  opportunity_id: z.string().uuid(),

  /** Human-readable title. */
  title: z.string().min(1).max(255),

  /** Current review/approval status. */
  status: BusinessCaseStatusSchema.default("draft"),

  /**
   * IDs of validated ValueHypothesis objects included in this case.
   * Only hypotheses with status "validated" may be included.
   */
  hypothesis_ids: z.array(z.string().uuid()).min(1),

  /** Rolled-up financial summary across all included hypotheses. */
  financial_summary: FinancialSummarySchema.nullable().optional(),

  /**
   * Version counter. Incremented each time the case is regenerated.
   * Enables audit trail and rollback.
   */
  version: z.number().int().positive().default(1),

  /** User ID of the person who owns/presents this case. */
  owner_id: z.string().uuid(),

  /** ISO 8601 timestamps. */
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export type BusinessCase = z.infer<typeof BusinessCaseSchema>;
