/**
 * BusinessCase — canonical domain object
 *
 * The customer-facing artifact that packages validated hypotheses, financial
 * models, and evidence into a presentable business case document.
 * Generated by ArtifactComposer (Sprint 4 target).
 *
 * Consolidates:
 * - BusinessCase interface (packages/backend/src/services/PersistenceService.ts)
 * - Value case concept (packages/backend/src/api/valueCases/types.ts)
 *
 * Sprint 3: First-class domain definition.
 */

import { z } from "zod";

export const BusinessCaseStatusSchema = z.enum([
  "draft",
  "in_review",
  "approved",
  "presented",
  "archived",
]);
export type BusinessCaseStatus = z.infer<typeof BusinessCaseStatusSchema>;

export const FinancialSummarySchema = z.object({
  /** Total value range across all validated hypotheses. */
  total_value_low_usd: z.number().nonnegative(),
  total_value_high_usd: z.number().nonnegative(),

  /** Payback period in months. */
  payback_months: z.number().positive().nullable().optional(),

  /** 3-year ROI as a multiplier (e.g. 3.2 = 320% ROI). */
  roi_3yr: z.number().nullable().optional(),

  /** IRR as a decimal (e.g. 0.45 = 45%). */
  irr: z.number().nullable().optional(),

  /** Currency code (ISO 4217). */
  currency: z.string().length(3).default("USD"),
});
export type FinancialSummary = z.infer<typeof FinancialSummarySchema>;

export const BusinessCaseSchema = z.object({
  /** Stable internal identifier (UUID). */
  id: z.string().uuid(),

  /** Tenant that owns this record. All queries must filter on this. */
  organization_id: z.string().uuid(),

  /** The opportunity this business case belongs to. */
  opportunity_id: z.string().uuid(),

  /** Human-readable title. */
  title: z.string().min(1).max(255),

  /** Current review/approval status. */
  status: BusinessCaseStatusSchema.default("draft"),

  /**
   * IDs of validated ValueHypothesis objects included in this case.
   * Only hypotheses with status "validated" may be included.
   */
  hypothesis_ids: z.array(z.string().uuid()).min(1),

  /** Rolled-up financial summary across all included hypotheses. */
  financial_summary: FinancialSummarySchema.nullable().optional(),

  /**
   * Version counter. Incremented each time the case is regenerated.
   * Enables audit trail and rollback.
   */
  version: z.number().int().positive().default(1),

  /** User ID of the person who owns/presents this case. */
  owner_id: z.string().uuid(),

  /**
   * Defense readiness score (0–1).
   *
   * Measures how well the business case can withstand scrutiny.
   * Calculated from two signals:
   *   - assumption validation rate: fraction of assumptions with human_reviewed=true
   *   - evidence strength: mean grounding_score across attached evidence items
   *
   * Score = 0.6 * assumption_validation_rate + 0.4 * mean_evidence_grounding_score
   *
   * A score ≥ 0.8 is considered presentation-ready.
   * A score < 0.4 indicates the case has unvalidated assumptions or weak evidence.
   *
   * Caller-populated: compute via calculateDefenseReadiness() in
   * packages/backend/src/domain/business-case/defenseReadiness.ts and write
   * the result back before persisting. ArtifactComposer computes this
   * automatically and exposes it on StakeholderView.defense_readiness_score.
   */
  defense_readiness_score: z.number().min(0).max(1).nullable().optional(),

  /**
   * Composite integrity score (0–1). Sprint 53.
   *
   * Measures internal consistency of the business case across all agent outputs.
   * Computed by ValueIntegrityService after each agent run:
   *
   *   integrity_score = 0.5 * defense_readiness_score
   *                   + 0.5 * (1 - Σ violation_penalties)
   *
   * Penalties: critical → 0.20, warning → 0.05, info → 0.01.
   * Dismissed violations carry a transparency penalty (critical → 0.05, warning → 0.01).
   * Score is clamped to [0, 1].
   *
   * A score < 0.6 with open critical violations blocks status advance to in_review.
   * NULL until ValueIntegrityService first runs for this case.
   */
  integrity_score: z.number().min(0).max(1).nullable().optional(),

  /**
   * Explicit integrity check result for gating decisions.
   * TRUE if integrity_score >= 0.6 and no critical violations.
   * Set by ValueIntegrityService during evaluation.
   */
  integrity_check_passed: z.boolean().nullable().optional(),

  /**
   * When integrity was last evaluated (ISO 8601 timestamp).
   * Used for audit trail and caching decisions.
   */
  integrity_evaluated_at: z.string().datetime().nullable().optional(),

  /**
   * Reason for veto if integrity check blocks stage advancement.
   * Populated when integrity_check_passed is false.
   */
  veto_reason: z.string().nullable().optional(),

  /** ISO 8601 timestamps. */
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export type BusinessCase = z.infer<typeof BusinessCaseSchema>;
