/**
 * RealizationPlan — canonical domain object
 *
 * The implementation plan that tracks whether committed value is actually
 * being realized post-sale. Generated by RealizationAgent.
 *
 * Consolidates:
 * - RealizationAnalysisSchema (packages/backend/src/lib/agent-fabric/agents/RealizationAgent.ts)
 * - ProofPointSchema, InterventionSchema from the same file
 *
 * Sprint 3: First-class domain definition.
 */

import { z } from "zod";

export const MilestoneStatusSchema = z.enum([
  "not_started",
  "in_progress",
  "completed",
  "at_risk",
  "missed",
]);
export type MilestoneStatus = z.infer<typeof MilestoneStatusSchema>;

export const MilestoneSchema = z.object({
  id: z.string().uuid(),

  /** Short description of what must be achieved. */
  description: z.string().min(1).max(500),

  /** The KPI target this milestone is tied to. */
  kpi_id: z.string().uuid().nullable().optional(),

  /** Target completion date (ISO 8601 date string). */
  due_date: z.string().date(),

  status: MilestoneStatusSchema.default("not_started"),

  /**
   * Realized value at this milestone.
   * Null until the milestone is completed and measured.
   */
  realized_value: z.number().nullable().optional(),

  /** Unit of the realized value (matches the associated KPI unit). */
  realized_value_unit: z.string().max(50).nullable().optional(),

  /** IDs of Evidence objects that prove this milestone was completed. */
  evidence_ids: z.array(z.string().uuid()).default([]),
});
export type Milestone = z.infer<typeof MilestoneSchema>;

export const RealizationPlanStatusSchema = z.enum([
  "active",
  "on_track",
  "at_risk",
  "completed",
  "abandoned",
]);
export type RealizationPlanStatus = z.infer<typeof RealizationPlanStatusSchema>;

export const RealizationPlanSchema = z.object({
  /** Stable internal identifier (UUID). */
  id: z.string().uuid(),

  /** Tenant that owns this record. All queries must filter on this. */
  organization_id: z.string().uuid(),

  /** The opportunity this plan belongs to. */
  opportunity_id: z.string().uuid(),

  /** The business case this plan is executing against. */
  business_case_id: z.string().uuid(),

  status: RealizationPlanStatusSchema.default("active"),

  /** Ordered list of milestones. */
  milestones: z.array(MilestoneSchema).min(1),

  /**
   * Overall realization rate 0–2 (1.0 = exactly on target).
   * Computed by RealizationAgent from proof points.
   */
  overall_realization_rate: z.number().min(0).max(2).nullable().optional(),

  /** ISO 8601 timestamps. */
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export type RealizationPlan = z.infer<typeof RealizationPlanSchema>;
