/**
 * ValueHypothesis — canonical domain object
 *
 * A testable claim that a specific intervention will produce a measurable
 * business outcome. Generated by OpportunityAgent; validated by IntegrityAgent.
 *
 * Consolidates:
 * - ValueHypothesis interface (packages/backend/src/lib/agents/orchestration/HypothesisLoop.ts)
 * - hypothesis_outputs table schema (Supabase migrations under infra/supabase/supabase/migrations/)
 * - ValueHypothesisSchema (packages/backend/src/services/AgentChatService.ts)
 *
 * Sprint 3: First-class domain definition. Agents must store and retrieve
 * hypotheses via this schema — not ad-hoc shapes.
 */

import { z } from "zod";

export const HypothesisConfidenceSchema = z.enum(["high", "medium", "low"]);
export type HypothesisConfidence = z.infer<typeof HypothesisConfidenceSchema>;

export const HypothesisStatusSchema = z.enum([
  "proposed",
  "under_review",
  "validated",
  "rejected",
  "superseded",
]);
export type HypothesisStatus = z.infer<typeof HypothesisStatusSchema>;

export const ValueRangeSchema = z.object({
  low: z.number(),
  high: z.number(),
  unit: z.enum(["usd", "percent", "hours", "headcount"]),
  timeframe_months: z.number().int().positive(),
});
export type ValueRange = z.infer<typeof ValueRangeSchema>;

export const ValueHypothesisSchema = z.object({
  /** Stable internal identifier (UUID). */
  id: z.string().uuid(),

  /** Tenant that owns this record. All queries must filter on this. */
  organization_id: z.string().uuid(),

  /** The opportunity this hypothesis belongs to. */
  opportunity_id: z.string().uuid(),

  /**
   * Human-readable claim. Must be falsifiable.
   * Example: "Automating invoice reconciliation will reduce DSO by 12 days."
   */
  description: z.string().min(10).max(2000),

  /** Value driver category (e.g. "cost_reduction", "revenue_acceleration"). */
  category: z.string().min(1).max(100),

  /** Quantified value range. Null until FinancialModelingAgent runs. */
  estimated_value: ValueRangeSchema.nullable().optional(),

  /** Agent-assigned confidence level. */
  confidence: HypothesisConfidenceSchema,

  /** Lifecycle status. */
  status: HypothesisStatusSchema.default("proposed"),

  /**
   * IDs of Evidence objects that support this hypothesis.
   * Populated by IntegrityAgent during validation.
   */
  evidence_ids: z.array(z.string().uuid()).default([]),

  /**
   * Hallucination check flag set by secureInvoke.
   * True = passed multi-signal grounding check.
   */
  hallucination_check: z.boolean().optional(),

  /** ISO 8601 timestamps. */
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export type ValueHypothesis = z.infer<typeof ValueHypothesisSchema>;
