/**
 * Service for managing Value Models, Business Cases, and their related artifacts.
 * This service encapsulates business logic and uses repositories for data access.
 */
import { logger } from "../../lib/logger.js"
import { KpiTargetRepository } from "../../repositories/KpiTargetRepository";
import { RoiModelCalculationRepository } from "../../repositories/RoiModelCalculationRepository";
import { RoiModelRepository } from "../../repositories/RoiModelRepository";
import { ValueCommitRepository } from "../../repositories/ValueCommitRepository";
import { ValueTreeLinkRepository } from "../../repositories/ValueTreeLinkRepository";
import { ValueTreeNodeRepository } from "../../repositories/ValueTreeNodeRepository";
import { ValueTreeRepository } from "../../repositories/ValueTreeRepository";
import { TargetAgentOutput } from "../../types/vos";
import { LifecycleContext } from "../types/agent";

import { auditLogService } from "./AuditLogService.js"
import { userSettingsService } from "./UserSettingsService.js"


export class ModelService {
  private context: LifecycleContext;
  private roiModelRepo: RoiModelRepository;
  private kpiTargetRepo: KpiTargetRepository;
  private valueTreeRepo: ValueTreeRepository;
  private valueTreeNodeRepo: ValueTreeNodeRepository;
  private valueTreeLinkRepo: ValueTreeLinkRepository;
  private roiModelCalcRepo: RoiModelCalculationRepository;
  private valueCommitRepo: ValueCommitRepository;

  constructor(context: LifecycleContext) {
    const tenantId = context.organization_id;
    if (!tenantId) {
      throw new Error("Tenant ID (organization_id) is required to initialize ModelService");
    }
    this.context = context;
    this.roiModelRepo = new RoiModelRepository();
    this.kpiTargetRepo = new KpiTargetRepository();
    this.valueTreeRepo = new ValueTreeRepository();
    this.valueTreeNodeRepo = new ValueTreeNodeRepository();
    this.valueTreeLinkRepo = new ValueTreeLinkRepository();
    this.roiModelCalcRepo = new RoiModelCalculationRepository();
    this.valueCommitRepo = new ValueCommitRepository();
  }

  /**
   * Helper to resolve audit actor details with fallback
   */
  private async resolveAuditActor(): Promise<{
    userId: string;
    userName: string;
    userEmail: string;
  }> {
    const userId = this.context.user_id;
    const tenantId = this.context.organization_id;

    try {
      if (!tenantId) throw new Error("No tenant ID in context");

      const profile = await userSettingsService.getProfile(userId, tenantId);
      return {
        userId,
        userName: profile.fullName || "Unknown User",
        userEmail: profile.email || "unknown@local",
      };
    } catch (error) {
      logger.warn("Failed to resolve user profile for audit logging", {
        userId,
        error,
      });
      return {
        userId,
        userName: "Unknown User",
        userEmail: "unknown@local",
      };
    }
  }

  /**
   * Persists all artifacts generated by the TargetAgent.
   * This encapsulates the logic previously in `TargetAgent.persistTargetArtifacts`.
   * @param output The output from the TargetAgent.
   * @param valueCaseId The ID of the value case.
   */
  async persistBusinessCase(
    output: TargetAgentOutput,
    valueCaseId: string
  ): Promise<{
    valueTreeId: string;
    roiModelId: string;
    valueCommitId: string;
  }> {
    // Resolve audit actor once
    const auditActor = await this.resolveAuditActor();
    const auditPromises: Promise<void>[] = [];

    // Track created artifacts for rollback
    const createdArtifacts: {
      valueTreeId?: string;
      roiModelId?: string;
      valueCommitId?: string;
    } = {};

    // Helper to log audit entry
    const logAudit = (
      resourceType: string,
      resourceId: string,
      details?: Record<string, unknown>
    ) => {
      const promise = auditLogService
        .logAudit({
          userId: auditActor.userId,
          userName: auditActor.userName,
          userEmail: auditActor.userEmail,
          action: "create",
          resourceType,
          resourceId,
          details,
        })
        .catch((err) => {
          logger.error(
            "Failed to write audit log",
            err instanceof Error ? err : new Error(String(err)),
            { resourceType, resourceId }
          );
        });
      auditPromises.push(promise);
    };

    try {
      // 1. Create Value Tree
      const { data: valueTreeData, error: treeError } =
        await this.valueTreeRepo.create({
          ...output.valueTree,
          value_case_id: valueCaseId,
        });
      if (treeError)
        throw new Error(`Failed to create value tree: ${treeError.message}`);
      const valueTreeId = valueTreeData.id;
      createdArtifacts.valueTreeId = valueTreeId;

      // Log provenance for value_tree creation
      logAudit("value_tree", valueTreeId, {
        name: (output.valueTree as Record<string, unknown>)?.name ?? "Unnamed",
        value_case_id: valueCaseId,
      });

      // 2. Create Value Tree Nodes and Links
      const bcNodes = ((output.businessCase ?? {}) as Record<string, unknown>).nodes as Array<Record<string, unknown>> ?? [];
      const bcLinks = ((output.businessCase ?? {}) as Record<string, unknown>).links as Array<Record<string, unknown>> ?? [];
      for (const node of bcNodes) {
        await this.valueTreeNodeRepo.create({
          value_tree_id: valueTreeId,
          node_id: node.node_id,
          label: node.label,
          type: node.type,
          reference_id: node.reference_id,
          properties: {},
        });
      }
      for (const link of bcLinks) {
        const { data: parentNode } = await this.valueTreeNodeRepo.findById(
          String(link.parent_node_id)
        );
        const { data: childNode } = await this.valueTreeNodeRepo.findById(
          String(link.child_node_id)
        );

        if (parentNode && childNode) {
          await this.valueTreeLinkRepo.create({
            value_tree_id: valueTreeId,
            parent_id: parentNode.id,
            child_id: childNode.id,
            link_type: "drives",
            weight: link.weight || 1.0,
            metadata: {},
          });
        }
      }

      // 3. Create ROI Model
      const roiModelInput = output.roiModel ?? {};
      const { data: roiModelData, error: roiError } =
        await this.roiModelRepo.create({
          ...roiModelInput,
          value_tree_id: valueTreeId,
        });
      if (roiError)
        throw new Error(`Failed to create ROI model: ${roiError.message}`);
      const roiModelId = roiModelData.id;
      createdArtifacts.roiModelId = roiModelId;

      // Log provenance for roi_model creation
      logAudit("roi_model", roiModelId, {
        name: (roiModelInput as Record<string, unknown>).name ?? "Unnamed",
        value_tree_id: valueTreeId,
      });

      // 4. Create ROI Model Calculations
      const bc = (output.businessCase ?? {}) as Record<string, unknown>;
      const calculations = (bc.calculations as Array<Record<string, unknown>>) ?? [];
      for (const calc of calculations) {
        const { data: calcData } = await this.roiModelCalcRepo.create({
          roi_model_id: roiModelId,
          ...calc,
          input_variables: calc.input_variables || [],
          source_references: calc.source_references || {},
          reasoning_trace:
            calc.reasoning_trace || bc.reasoning,
        });

        // Log provenance for calculation creation
        if (calcData && calcData.id) {
          logAudit("calculation", calcData.id, {
            name: calc.name,
            roi_model_id: roiModelId,
            formula: calc.formula,
          });
        }
      }

      // 5. Create Value Commit
      const valueCommitInput = (output as unknown as Record<string, unknown>).valueCommit as Record<string, unknown> ?? {};
      const { data: commitData, error: commitError } =
        await this.valueCommitRepo.create({
          ...valueCommitInput,
          value_tree_id: valueTreeId,
          value_case_id: valueCaseId,
        });
      if (commitError)
        throw new Error(
          `Failed to create value commit: ${commitError.message}`
        );
      const valueCommitId = commitData.id;
      createdArtifacts.valueCommitId = valueCommitId;

      // Log provenance for value_commit creation
      logAudit("value_commit", valueCommitId, {
        value_tree_id: valueTreeId,
        value_case_id: valueCaseId,
      });

      // 6. Create KPI Targets
      const kpiTargets = (bc.kpi_targets as Array<Record<string, unknown>>) ?? [];
      for (const target of kpiTargets) {
        await this.kpiTargetRepo.create({
          value_commit_id: valueCommitId,
          kpi_hypothesis_id: "", // This seems to be missing from the agent output
          ...target,
        });
      }

      // Await all audit logs (best effort)
      await Promise.allSettled(auditPromises);

      return { valueTreeId, roiModelId, valueCommitId };
    } catch (error) {
      logger.error(
        "Transaction failed in persistBusinessCase, rolling back...",
        {
          error,
          createdArtifacts,
        }
      );

      // Manual Rollback / Compensation
      // Delete in reverse order of creation
      // Compensation: delete in reverse order of creation
      // Repositories are stubs — delete is a no-op until implemented
      const deleteIfExists = async (repo: { findById: (id: string) => Promise<unknown> }, id: string, label: string) => {
        try {
          const deleteMethod = (repo as unknown as Record<string, unknown>).delete;
          if (typeof deleteMethod === "function") {
            await (deleteMethod as (id: string) => Promise<void>)(id);
          } else {
            logger.warn(`Rollback skipped: ${label} repository has no delete method`, { id });
          }
        } catch (rollbackError) {
          logger.error(`Failed to rollback ${label}`, { rollbackError });
        }
      };

      if (createdArtifacts.valueCommitId) {
        await deleteIfExists(this.valueCommitRepo, createdArtifacts.valueCommitId, "value commit");
      }
      if (createdArtifacts.roiModelId) {
        await deleteIfExists(this.roiModelRepo, createdArtifacts.roiModelId, "ROI model");
      }
      if (createdArtifacts.valueTreeId) {
        await deleteIfExists(this.valueTreeRepo, createdArtifacts.valueTreeId, "value tree");
      }

      throw error;
    }
  }
}
