/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user profile */
        get: operations["getAuthenticatedUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI tutor chat interaction */
        post: operations["chatWithTutor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/roi-narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate ROI narrative */
        post: operations["generateRoiNarrative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/value-case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate value case */
        post: operations["generateValueCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pillars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the VOS capability pillars */
        get: operations["listPillars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pillars/{pillarNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pillar by number */
        get: operations["getPillarByNumber"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pillars/{pillarNumber}/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get knowledge-check questions for a pillar */
        get: operations["getQuizQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit quiz answers */
        post: operations["submitQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List simulation scenarios */
        get: operations["listSimulations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{scenarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get simulation scenario */
        get: operations["getSimulationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{scenarioId}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a simulation attempt */
        post: operations["submitSimulationAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List certifications for the learner */
        get: operations["listCertifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /**
             * @example customer
             * @example internal
             */
            role: string;
            maturityLevel: string;
            name?: string;
        };
        Message: {
            /** @enum {string} */
            role: "system" | "user" | "assistant";
            content: string;
        };
        ChatRequest: {
            messages: components["schemas"]["Message"][];
        };
        ChatResponse: {
            content: string;
            /** @description Optional tutor annotations or rubric notes. */
            annotations?: string[];
        };
        ROINarrativeRequest: {
            businessCase: string;
            benefits: string[];
            costs: {
                implementation: number;
                licensing?: number;
                training?: number;
            };
            /** @enum {string} */
            timeframe: "1year" | "2years" | "3years";
            /** @enum {string} */
            audience: "executive" | "finance" | "technical";
        };
        ROINarrativeResponse: {
            narrative: string;
            financials: {
                totalCosts: number;
                totalBenefits: number;
                roi: number;
                paybackPeriod?: number;
            };
        };
        ValueCaseRequest: {
            pillarId: number;
            outcomes: string[];
            capabilities: string[];
            kpis: {
                name: string;
                baseline: number;
                target: number;
                timeframe: string;
            }[];
            costs: {
                implementation: number;
                licensing?: number;
                training?: number;
            };
            /** @enum {string} */
            audience: "executive" | "finance" | "technical";
        };
        ValueCaseResponse: {
            valueCase: string;
            roi: number;
            estimatedBenefits?: number;
        };
        Pillar: {
            id: number;
            pillarNumber: number;
            title: string;
            description: string;
            focusAreas?: string[];
        };
        QuizQuestion: {
            id: number;
            pillarNumber: number;
            prompt: string;
            options: {
                id: number;
                label: string;
                value: string;
                correct?: boolean;
            }[];
        };
        QuizSubmission: {
            pillarNumber: number;
            answers: {
                questionId: number;
                answer: string;
            }[];
            context?: string;
        };
        QuizSubmissionResult: {
            score: number;
            passed: boolean;
            feedback: string[];
        };
        SimulationScenario: {
            id: number;
            title: string;
            description: string;
            pillarNumber: number;
            /** @enum {string} */
            difficulty: "foundation" | "advanced" | "expert";
            domain?: string;
            customerPersona?: string;
            tasks?: {
                id: number;
                title: string;
                prompt: string;
            }[];
        };
        SimulationAttempt: {
            scenarioId: number;
            response: string;
            stage?: string;
        };
        SimulationAttemptResult: {
            score: number;
            feedback: string[];
            nextSteps?: string[];
        };
        Certification: {
            id: number;
            name: string;
            score: number;
            /** @enum {string} */
            tier: "bronze" | "silver" | "gold";
            /** Format: uri */
            downloadUrl?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthenticatedUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User is authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    chatWithTutor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Tutor response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
        };
    };
    generateRoiNarrative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ROINarrativeRequest"];
            };
        };
        responses: {
            /** @description Narrative generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ROINarrativeResponse"];
                };
            };
        };
    };
    generateValueCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValueCaseRequest"];
            };
        };
        responses: {
            /** @description Value case generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValueCaseResponse"];
                };
            };
        };
    };
    listPillars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of pillars */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Pillar"][];
                    };
                };
            };
        };
    };
    getPillarByNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pillarNumber: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pillar details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pillar"];
                };
            };
            /** @description Pillar not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getQuizQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pillarNumber: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quiz questions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        questions: components["schemas"]["QuizQuestion"][];
                    };
                };
            };
        };
    };
    submitQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmission"];
            };
        };
        responses: {
            /** @description Quiz graded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizSubmissionResult"];
                };
            };
        };
    };
    listSimulations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenarios available */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        scenarios: components["schemas"]["SimulationScenario"][];
                    };
                };
            };
        };
    };
    getSimulationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationScenario"];
                };
            };
            /** @description Scenario not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitSimulationAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationAttempt"];
            };
        };
        responses: {
            /** @description Attempt graded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationAttemptResult"];
                };
            };
        };
    };
    listCertifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Certification badges */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        certifications: components["schemas"]["Certification"][];
                    };
                };
            };
        };
    };
}
