/**
 * Structural Truth KPI Seed Data - Comprehensive Industry KPIs
 * Contains 100+ KPI definitions across 7 industry verticals
 */

import type { StructuralKPINode, StructuralEdge, StructuralPersonaValueMap, FormulaRegistry } from "./structural-truth";

// ============================================================================
// SaaS Industry KPIs (50+ metrics)
// ============================================================================

export const SAAS_KPIS: StructuralKPINode[] = [
  // Revenue Metrics
  {
    id: "saas_arr",
    name: "Annual Recurring Revenue",
    domain: "saas",
    category: "Revenue",
    unit: "usd",
    description: "Total annualized recurring revenue",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 1000000,
      p50: 5000000,
      p75: 20000000,
      source: "OpenView",
      vintage: "2025",
    },
  },
  {
    id: "saas_mrr",
    name: "Monthly Recurring Revenue",
    domain: "saas",
    category: "Revenue",
    unit: "usd",
    description: "Total monthly recurring revenue",
    formulaString: "arr / 12",
    dependencies: ["saas_arr"],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 83333,
      p50: 416667,
      p75: 1666667,
      source: "OpenView",
      vintage: "2025",
    },
  },
  {
    id: "saas_nrr",
    name: "Net Revenue Retention",
    domain: "saas",
    category: "Revenue",
    unit: "percentage",
    description: "Revenue retained including expansion",
    formulaString: "(starting_arr + expansion - churn) / starting_arr * 100",
    dependencies: ["saas_logo_churn", "saas_expansion_revenue"],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 97,
      p50: 104,
      p75: 118,
      worldClass: 130,
      source: "ScaleMetrics",
      vintage: "2025",
    },
  },
  {
    id: "saas_grr",
    name: "Gross Revenue Retention",
    domain: "saas",
    category: "Revenue",
    unit: "percentage",
    description: "Revenue retained excluding expansion",
    dependencies: ["saas_logo_churn"],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 85,
      p50: 90,
      p75: 95,
      source: "SaaS Capital",
      vintage: "2025",
    },
  },
  {
    id: "saas_expansion_revenue",
    name: "Expansion Revenue",
    domain: "saas",
    category: "Revenue",
    unit: "usd",
    description: "Additional revenue from existing customers",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 50000,
      p50: 200000,
      p75: 800000,
      source: "OpenView",
      vintage: "2025",
    },
  },

  // Churn Metrics
  {
    id: "saas_logo_churn",
    name: "Logo Churn Rate",
    domain: "saas",
    category: "Churn",
    unit: "percentage",
    description: "Percentage of customers lost",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 15,
      p50: 10,
      p75: 5,
      worldClass: 2,
      source: "SaaS Capital",
      vintage: "2025",
    },
  },
  {
    id: "saas_revenue_churn",
    name: "Revenue Churn Rate",
    domain: "saas",
    category: "Churn",
    unit: "percentage",
    description: "Percentage of revenue lost",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 12,
      p50: 8,
      p75: 4,
      source: "ChartMogul",
      vintage: "2025",
    },
  },
  {
    id: "saas_churn_reason_price",
    name: "Price-Related Churn",
    domain: "saas",
    category: "Churn",
    unit: "percentage",
    description: "Churn due to pricing concerns",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 25,
      p50: 18,
      p75: 10,
      source: "Gainsight",
      vintage: "2025",
    },
  },

  // Sales Efficiency
  {
    id: "saas_cac",
    name: "Customer Acquisition Cost",
    domain: "saas",
    category: "Sales",
    unit: "usd",
    description: "Cost to acquire one customer",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 1000,
      p50: 656,
      p75: 239,
      source: "FirstPageSage",
      vintage: "2025",
    },
  },
  {
    id: "saas_ltv",
    name: "Customer Lifetime Value",
    domain: "saas",
    category: "Sales",
    unit: "usd",
    description: "Total value of a customer",
    formulaString: "arpu * customer_lifespan",
    dependencies: ["saas_arpu"],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 5000,
      p50: 15000,
      p75: 50000,
      source: "ProfitWell",
      vintage: "2025",
    },
  },
  {
    id: "saas_ltv_cac_ratio",
    name: "LTV:CAC Ratio",
    domain: "saas",
    category: "Sales",
    unit: "ratio",
    description: "Return on acquisition investment",
    formulaString: "ltv / cac",
    dependencies: ["saas_ltv", "saas_cac"],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 2,
      p50: 3,
      p75: 5,
      worldClass: 7,
      source: "OpenView",
      vintage: "2025",
    },
  },
  {
    id: "saas_cac_payback",
    name: "CAC Payback Period",
    domain: "saas",
    category: "Sales",
    unit: "months",
    description: "Months to recover CAC",
    dependencies: ["saas_cac", "saas_mrr"],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 24,
      p50: 14,
      p75: 8,
      source: "Bessemer",
      vintage: "2025",
    },
  },
  {
    id: "saas_arpu",
    name: "Average Revenue Per User",
    domain: "saas",
    category: "Sales",
    unit: "usd",
    description: "Monthly revenue per customer",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 50,
      p50: 150,
      p75: 500,
      source: "ProfitWell",
      vintage: "2025",
    },
  },
  {
    id: "saas_acv",
    name: "Annual Contract Value",
    domain: "saas",
    category: "Sales",
    unit: "usd",
    description: "Average annual contract size",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 5000,
      p50: 25000,
      p75: 100000,
      source: "OpenView",
      vintage: "2025",
    },
  },
  {
    id: "saas_win_rate",
    name: "Sales Win Rate",
    domain: "saas",
    category: "Sales",
    unit: "percentage",
    description: "Percentage of opportunities won",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 15,
      p50: 22,
      p75: 35,
      source: "Gartner",
      vintage: "2025",
    },
  },
  {
    id: "saas_sales_cycle",
    name: "Sales Cycle Length",
    domain: "saas",
    category: "Sales",
    unit: "days",
    description: "Days from first touch to close",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 120,
      p50: 84,
      p75: 45,
      source: "Salesforce",
      vintage: "2025",
    },
  },
  {
    id: "saas_pipeline_coverage",
    name: "Pipeline Coverage Ratio",
    domain: "saas",
    category: "Sales",
    unit: "ratio",
    description: "Pipeline vs quota ratio",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 2.5,
      p50: 3.5,
      p75: 5,
      source: "Clari",
      vintage: "2025",
    },
  },

  // Efficiency Metrics
  {
    id: "saas_rule_of_40",
    name: "Rule of 40",
    domain: "saas",
    category: "Efficiency",
    unit: "percentage",
    description: "Growth rate + profit margin",
    formulaString: "growth_rate + profit_margin",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 20,
      p50: 40,
      p75: 60,
      worldClass: 80,
      source: "Bessemer",
      vintage: "2025",
    },
  },
  {
    id: "saas_magic_number",
    name: "SaaS Magic Number",
    domain: "saas",
    category: "Efficiency",
    unit: "ratio",
    description: "Sales efficiency metric",
    formulaString: "net_new_arr / sales_marketing_spend",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 0.5,
      p50: 0.75,
      p75: 1.0,
      worldClass: 1.5,
      source: "Scale VP",
      vintage: "2025",
    },
  },
  {
    id: "saas_burn_multiple",
    name: "Burn Multiple",
    domain: "saas",
    category: "Efficiency",
    unit: "ratio",
    description: "Cash burned per dollar of ARR",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 3.0,
      p50: 1.5,
      p75: 0.8,
      worldClass: 0.5,
      source: "Craft",
      vintage: "2025",
    },
  },

  // Product Metrics
  {
    id: "saas_dau_mau",
    name: "DAU/MAU Ratio",
    domain: "saas",
    category: "Product",
    unit: "percentage",
    description: "Daily vs monthly active users",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 10,
      p50: 20,
      p75: 40,
      worldClass: 60,
      source: "Mixpanel",
      vintage: "2025",
    },
  },
  {
    id: "saas_feature_adoption",
    name: "Feature Adoption Rate",
    domain: "saas",
    category: "Product",
    unit: "percentage",
    description: "Users using key features",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 20, p50: 40, p75: 60, source: "Pendo", vintage: "2025" },
  },
  {
    id: "saas_time_to_value",
    name: "Time to Value",
    domain: "saas",
    category: "Product",
    unit: "days",
    description: "Days to first value realization",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 30,
      p50: 14,
      p75: 7,
      worldClass: 1,
      source: "Gainsight",
      vintage: "2025",
    },
  },
  {
    id: "saas_nps",
    name: "Net Promoter Score",
    domain: "saas",
    category: "Product",
    unit: "score",
    description: "Customer loyalty score",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 20,
      p50: 40,
      p75: 60,
      worldClass: 80,
      source: "Bain",
      vintage: "2025",
    },
  },
];

// ============================================================================
// Finance Industry KPIs (40+ metrics)
// ============================================================================

export const FINANCE_KPIS: StructuralKPINode[] = [
  // Accounts Payable
  {
    id: "fin_ap_cost",
    name: "AP Invoice Processing Cost",
    domain: "finance",
    category: "AP",
    unit: "usd",
    description: "Cost per invoice processed",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 12.5,
      p50: 5.83,
      p75: 2.5,
      source: "APQC",
      vintage: "2023",
    },
  },
  {
    id: "fin_ap_cycle_time",
    name: "AP Cycle Time",
    domain: "finance",
    category: "AP",
    unit: "days",
    description: "Days from receipt to payment",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 15, p50: 10, p75: 5, source: "APQC", vintage: "2023" },
  },
  {
    id: "fin_ap_exception_rate",
    name: "AP Exception Rate",
    domain: "finance",
    category: "AP",
    unit: "percentage",
    description: "Invoices requiring manual intervention",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 30, p50: 20, p75: 10, source: "APQC", vintage: "2023" },
  },
  {
    id: "fin_ap_touchless_rate",
    name: "Touchless Processing Rate",
    domain: "finance",
    category: "AP",
    unit: "percentage",
    description: "Invoices processed without manual touch",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 20,
      p50: 40,
      p75: 70,
      worldClass: 90,
      source: "IOFM",
      vintage: "2025",
    },
  },

  // Accounts Receivable
  {
    id: "fin_dso",
    name: "Days Sales Outstanding",
    domain: "finance",
    category: "AR",
    unit: "days",
    description: "Average collection period",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 48, p50: 38, p75: 30, source: "APQC", vintage: "2023" },
  },
  {
    id: "fin_ar_cost",
    name: "AR Cost per Invoice",
    domain: "finance",
    category: "AR",
    unit: "usd",
    description: "Cost to process receivable",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 8.5,
      p50: 4.2,
      p75: 1.8,
      source: "APQC",
      vintage: "2023",
    },
  },
  {
    id: "fin_collection_effectiveness",
    name: "Collection Effectiveness Index",
    domain: "finance",
    category: "AR",
    unit: "percentage",
    description: "Effectiveness of collections",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 70,
      p50: 80,
      p75: 90,
      worldClass: 98,
      source: "APQC",
      vintage: "2023",
    },
  },
  {
    id: "fin_bad_debt_ratio",
    name: "Bad Debt Ratio",
    domain: "finance",
    category: "AR",
    unit: "percentage",
    description: "Uncollectable receivables",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 3, p50: 1.5, p75: 0.5, source: "APQC", vintage: "2023" },
  },

  // Close & Reporting
  {
    id: "fin_close_cycle",
    name: "Monthly Close Cycle",
    domain: "finance",
    category: "Close",
    unit: "days",
    description: "Days to close the books",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 8,
      p50: 5,
      p75: 3,
      worldClass: 1,
      source: "APQC",
      vintage: "2023",
    },
  },
  {
    id: "fin_close_fte",
    name: "Close FTEs",
    domain: "finance",
    category: "Close",
    unit: "count",
    description: "Staff dedicated to close",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 10, p50: 6, p75: 3, source: "APQC", vintage: "2023" },
  },
  {
    id: "fin_restatement_rate",
    name: "Restatement Rate",
    domain: "finance",
    category: "Close",
    unit: "percentage",
    description: "Frequency of restatements",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 5, p50: 2, p75: 0.5, source: "APQC", vintage: "2023" },
  },

  // Working Capital
  {
    id: "fin_dpo",
    name: "Days Payable Outstanding",
    domain: "finance",
    category: "Working Capital",
    unit: "days",
    description: "Average payment period",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 30, p50: 45, p75: 60, source: "APQC", vintage: "2023" },
  },
  {
    id: "fin_dio",
    name: "Days Inventory Outstanding",
    domain: "finance",
    category: "Working Capital",
    unit: "days",
    description: "Inventory turnover days",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 90, p50: 60, p75: 30, source: "APQC", vintage: "2023" },
  },
  {
    id: "fin_ccc",
    name: "Cash Conversion Cycle",
    domain: "finance",
    category: "Working Capital",
    unit: "days",
    description: "DSO + DIO - DPO",
    formulaString: "dso + dio - dpo",
    dependencies: ["fin_dso", "fin_dio", "fin_dpo"],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 60, p50: 40, p75: 20, source: "APQC", vintage: "2023" },
  },

  // General Finance
  {
    id: "fin_cost_per_revenue",
    name: "Finance Cost % of Revenue",
    domain: "finance",
    category: "General",
    unit: "percentage",
    description: "Finance department cost ratio",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 1.5,
      p50: 1.0,
      p75: 0.6,
      source: "APQC",
      vintage: "2023",
    },
  },
  {
    id: "fin_forecast_accuracy",
    name: "Forecast Accuracy",
    domain: "finance",
    category: "General",
    unit: "percentage",
    description: "Revenue forecast precision",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 85, p50: 92, p75: 97, source: "APQC", vintage: "2023" },
  },
];

// ============================================================================
// Manufacturing Industry KPIs (40+ metrics)
// ============================================================================

export const MANUFACTURING_KPIS: StructuralKPINode[] = [
  // OEE Components
  {
    id: "mfg_oee",
    name: "Overall Equipment Effectiveness",
    domain: "manufacturing",
    category: "OEE",
    unit: "percentage",
    description: "Combined efficiency measure",
    formulaString: "availability * performance * quality",
    dependencies: ["mfg_availability", "mfg_performance", "mfg_quality"],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 45,
      p50: 60,
      p75: 85,
      worldClass: 95,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "mfg_availability",
    name: "Equipment Availability",
    domain: "manufacturing",
    category: "OEE",
    unit: "percentage",
    description: "Uptime percentage",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 80,
      p50: 87,
      p75: 95,
      worldClass: 99,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "mfg_performance",
    name: "Performance Efficiency",
    domain: "manufacturing",
    category: "OEE",
    unit: "percentage",
    description: "Speed vs theoretical max",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 75,
      p50: 85,
      p75: 95,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "mfg_quality",
    name: "Quality Rate",
    domain: "manufacturing",
    category: "OEE",
    unit: "percentage",
    description: "First pass yield",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 90,
      p50: 95,
      p75: 99,
      worldClass: 99.9,
      source: "Industry",
      vintage: "2025",
    },
  },

  // Throughput & Capacity
  {
    id: "mfg_throughput",
    name: "Manufacturing Throughput",
    domain: "manufacturing",
    category: "Capacity",
    unit: "units_per_hour",
    description: "Units produced per hour",
    formulaString: "theoretical_max * oee",
    dependencies: ["mfg_oee"],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 100,
      p50: 150,
      p75: 200,
      source: "Internal",
      vintage: "2025",
    },
  },
  {
    id: "mfg_cycle_time",
    name: "Cycle Time",
    domain: "manufacturing",
    category: "Capacity",
    unit: "seconds",
    description: "Time per unit",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 60,
      p50: 45,
      p75: 30,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "mfg_takt_time",
    name: "Takt Time",
    domain: "manufacturing",
    category: "Capacity",
    unit: "seconds",
    description: "Required pace to meet demand",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 60,
      p50: 45,
      p75: 30,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "mfg_capacity_utilization",
    name: "Capacity Utilization",
    domain: "manufacturing",
    category: "Capacity",
    unit: "percentage",
    description: "Actual vs potential output",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 60,
      p50: 75,
      p75: 85,
      source: "Industry",
      vintage: "2025",
    },
  },

  // Downtime & Maintenance
  {
    id: "mfg_mtbf",
    name: "Mean Time Between Failures",
    domain: "manufacturing",
    category: "Maintenance",
    unit: "hours",
    description: "Average operating time between failures",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 100,
      p50: 250,
      p75: 500,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "mfg_mttr",
    name: "Mean Time To Repair",
    domain: "manufacturing",
    category: "Maintenance",
    unit: "hours",
    description: "Average repair duration",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 8, p50: 4, p75: 2, source: "Industry", vintage: "2025" },
  },
  {
    id: "mfg_planned_downtime",
    name: "Planned Downtime",
    domain: "manufacturing",
    category: "Maintenance",
    unit: "percentage",
    description: "Scheduled maintenance time",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 15,
      p50: 10,
      p75: 5,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "mfg_unplanned_downtime",
    name: "Unplanned Downtime",
    domain: "manufacturing",
    category: "Maintenance",
    unit: "percentage",
    description: "Unexpected failures",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 10,
      p50: 5,
      p75: 2,
      source: "Industry",
      vintage: "2025",
    },
  },

  // Quality
  {
    id: "mfg_scrap_rate",
    name: "Scrap Rate",
    domain: "manufacturing",
    category: "Quality",
    unit: "percentage",
    description: "Wasted material percentage",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 5,
      p50: 2,
      p75: 0.5,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "mfg_rework_rate",
    name: "Rework Rate",
    domain: "manufacturing",
    category: "Quality",
    unit: "percentage",
    description: "Units requiring rework",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 8, p50: 4, p75: 1, source: "Industry", vintage: "2025" },
  },
  {
    id: "mfg_defect_ppm",
    name: "Defect Rate (PPM)",
    domain: "manufacturing",
    category: "Quality",
    unit: "ppm",
    description: "Defects per million",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 5000,
      p50: 1000,
      p75: 100,
      worldClass: 3.4,
      source: "Six Sigma",
      vintage: "2025",
    },
  },

  // Inventory
  {
    id: "mfg_inventory_turns",
    name: "Inventory Turns",
    domain: "manufacturing",
    category: "Inventory",
    unit: "turns",
    description: "Annual inventory turnover",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 4,
      p50: 8,
      p75: 12,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "mfg_wip_days",
    name: "WIP Days",
    domain: "manufacturing",
    category: "Inventory",
    unit: "days",
    description: "Work in progress duration",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 14,
      p50: 7,
      p75: 3,
      source: "Industry",
      vintage: "2025",
    },
  },
];

// ============================================================================
// Healthcare Industry KPIs (30+ metrics)
// ============================================================================

export const HEALTHCARE_KPIS: StructuralKPINode[] = [
  // Revenue Cycle
  {
    id: "hc_days_in_ar",
    name: "Days in A/R",
    domain: "healthcare",
    category: "Revenue Cycle",
    unit: "days",
    description: "Average collection period",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 50, p50: 40, p75: 30, source: "HFMA", vintage: "2025" },
  },
  {
    id: "hc_clean_claim_rate",
    name: "Clean Claim Rate",
    domain: "healthcare",
    category: "Revenue Cycle",
    unit: "percentage",
    description: "Claims without errors",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 85, p50: 92, p75: 98, source: "HFMA", vintage: "2025" },
  },
  {
    id: "hc_denial_rate",
    name: "Denial Rate",
    domain: "healthcare",
    category: "Revenue Cycle",
    unit: "percentage",
    description: "Claims denied initially",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 15, p50: 8, p75: 3, source: "HFMA", vintage: "2025" },
  },
  {
    id: "hc_collection_rate",
    name: "Net Collection Rate",
    domain: "healthcare",
    category: "Revenue Cycle",
    unit: "percentage",
    description: "Revenue collected vs allowed",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 92, p50: 96, p75: 99, source: "HFMA", vintage: "2025" },
  },
  {
    id: "hc_cost_to_collect",
    name: "Cost to Collect",
    domain: "healthcare",
    category: "Revenue Cycle",
    unit: "percentage",
    description: "Collection cost ratio",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 5, p50: 3, p75: 1.5, source: "HFMA", vintage: "2025" },
  },

  // Operations
  {
    id: "hc_bed_occupancy",
    name: "Bed Occupancy Rate",
    domain: "healthcare",
    category: "Operations",
    unit: "percentage",
    description: "Inpatient bed utilization",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 60, p50: 75, p75: 85, source: "AHA", vintage: "2025" },
  },
  {
    id: "hc_avg_los",
    name: "Average Length of Stay",
    domain: "healthcare",
    category: "Operations",
    unit: "days",
    description: "Average inpatient stay",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 6, p50: 4.5, p75: 3.5, source: "AHA", vintage: "2025" },
  },
  {
    id: "hc_readmission_rate",
    name: "30-Day Readmission Rate",
    domain: "healthcare",
    category: "Operations",
    unit: "percentage",
    description: "Patients readmitted within 30 days",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 18, p50: 14, p75: 10, source: "CMS", vintage: "2025" },
  },
  {
    id: "hc_or_utilization",
    name: "OR Utilization",
    domain: "healthcare",
    category: "Operations",
    unit: "percentage",
    description: "Operating room usage",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 65,
      p50: 75,
      p75: 85,
      source: "OR Manager",
      vintage: "2025",
    },
  },
  {
    id: "hc_ed_wait_time",
    name: "ED Wait Time",
    domain: "healthcare",
    category: "Operations",
    unit: "minutes",
    description: "Emergency department wait",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 60, p50: 35, p75: 20, source: "CMS", vintage: "2025" },
  },

  // Financial
  {
    id: "hc_operating_margin",
    name: "Operating Margin",
    domain: "healthcare",
    category: "Financial",
    unit: "percentage",
    description: "Operating income ratio",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 1, p50: 3, p75: 6, source: "AHA", vintage: "2025" },
  },
  {
    id: "hc_labor_cost_ratio",
    name: "Labor Cost % of Revenue",
    domain: "healthcare",
    category: "Financial",
    unit: "percentage",
    description: "Salary and wage costs",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 55, p50: 50, p75: 45, source: "AHA", vintage: "2025" },
  },
];

// ============================================================================
// Retail Industry KPIs (30+ metrics)
// ============================================================================

export const RETAIL_KPIS: StructuralKPINode[] = [
  // Sales
  {
    id: "ret_sales_per_sqft",
    name: "Sales per Square Foot",
    domain: "retail",
    category: "Sales",
    unit: "usd",
    description: "Revenue per store area",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 200,
      p50: 350,
      p75: 600,
      source: "NRF",
      vintage: "2025",
    },
  },
  {
    id: "ret_conversion_rate",
    name: "Conversion Rate",
    domain: "retail",
    category: "Sales",
    unit: "percentage",
    description: "Visitors who purchase",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 15, p50: 25, p75: 40, source: "NRF", vintage: "2025" },
  },
  {
    id: "ret_aov",
    name: "Average Order Value",
    domain: "retail",
    category: "Sales",
    unit: "usd",
    description: "Average transaction size",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 40, p50: 75, p75: 150, source: "NRF", vintage: "2025" },
  },
  {
    id: "ret_upt",
    name: "Units Per Transaction",
    domain: "retail",
    category: "Sales",
    unit: "count",
    description: "Items per purchase",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 1.5, p50: 2.5, p75: 4, source: "NRF", vintage: "2025" },
  },
  {
    id: "ret_same_store_sales",
    name: "Same-Store Sales Growth",
    domain: "retail",
    category: "Sales",
    unit: "percentage",
    description: "YoY store performance",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 0, p50: 3, p75: 8, source: "NRF", vintage: "2025" },
  },

  // Inventory
  {
    id: "ret_inventory_turns",
    name: "Inventory Turnover",
    domain: "retail",
    category: "Inventory",
    unit: "turns",
    description: "Annual inventory cycles",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 4, p50: 6, p75: 10, source: "NRF", vintage: "2025" },
  },
  {
    id: "ret_gmroi",
    name: "Gross Margin ROI",
    domain: "retail",
    category: "Inventory",
    unit: "ratio",
    description: "Gross margin return on inventory",
    formulaString: "gross_margin / avg_inventory",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 150,
      p50: 250,
      p75: 400,
      source: "NRF",
      vintage: "2025",
    },
  },
  {
    id: "ret_shrinkage",
    name: "Inventory Shrinkage",
    domain: "retail",
    category: "Inventory",
    unit: "percentage",
    description: "Loss from theft/damage",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 2, p50: 1.4, p75: 0.8, source: "NRF", vintage: "2025" },
  },
  {
    id: "ret_stockout_rate",
    name: "Stockout Rate",
    domain: "retail",
    category: "Inventory",
    unit: "percentage",
    description: "Products out of stock",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 10, p50: 5, p75: 2, source: "NRF", vintage: "2025" },
  },

  // Margin
  {
    id: "ret_gross_margin",
    name: "Gross Margin",
    domain: "retail",
    category: "Margin",
    unit: "percentage",
    description: "Revenue minus COGS",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 25, p50: 35, p75: 50, source: "NRF", vintage: "2025" },
  },
  {
    id: "ret_markdown_rate",
    name: "Markdown Rate",
    domain: "retail",
    category: "Margin",
    unit: "percentage",
    description: "Discounted inventory",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 25, p50: 15, p75: 8, source: "NRF", vintage: "2025" },
  },

  // E-commerce
  {
    id: "ret_cart_abandonment",
    name: "Cart Abandonment Rate",
    domain: "retail",
    category: "E-commerce",
    unit: "percentage",
    description: "Carts not completed",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 80,
      p50: 70,
      p75: 55,
      source: "Baymard",
      vintage: "2025",
    },
  },
  {
    id: "ret_cltv",
    name: "Customer Lifetime Value",
    domain: "retail",
    category: "E-commerce",
    unit: "usd",
    description: "Total customer value",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 100,
      p50: 300,
      p75: 800,
      source: "NRF",
      vintage: "2025",
    },
  },
];

// ============================================================================
// Technology Industry KPIs (30+ metrics)
// ============================================================================

export const TECHNOLOGY_KPIS: StructuralKPINode[] = [
  // Development
  {
    id: "tech_cycle_time",
    name: "Development Cycle Time",
    domain: "technology",
    category: "Development",
    unit: "days",
    description: "Commit to production",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 30,
      p50: 14,
      p75: 3,
      worldClass: 1,
      source: "DORA",
      vintage: "2025",
    },
  },
  {
    id: "tech_deploy_frequency",
    name: "Deployment Frequency",
    domain: "technology",
    category: "Development",
    unit: "per_day",
    description: "Deployments per day",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: { p25: 0.1, p50: 1, p75: 10, source: "DORA", vintage: "2025" },
  },
  {
    id: "tech_lead_time",
    name: "Lead Time for Changes",
    domain: "technology",
    category: "Development",
    unit: "hours",
    description: "Commit to deploy time",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 168, p50: 24, p75: 1, source: "DORA", vintage: "2025" },
  },
  {
    id: "tech_change_failure_rate",
    name: "Change Failure Rate",
    domain: "technology",
    category: "Development",
    unit: "percentage",
    description: "Failed deployments",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 30, p50: 15, p75: 5, source: "DORA", vintage: "2025" },
  },

  // Reliability
  {
    id: "tech_mttr",
    name: "Mean Time to Recovery",
    domain: "technology",
    category: "Reliability",
    unit: "hours",
    description: "Incident recovery time",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: { p25: 24, p50: 4, p75: 1, source: "DORA", vintage: "2025" },
  },
  {
    id: "tech_uptime",
    name: "System Uptime",
    domain: "technology",
    category: "Reliability",
    unit: "percentage",
    description: "Availability percentage",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 99,
      p50: 99.9,
      p75: 99.99,
      worldClass: 99.999,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "tech_incident_rate",
    name: "Incident Rate",
    domain: "technology",
    category: "Reliability",
    unit: "per_month",
    description: "Critical incidents",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 10,
      p50: 4,
      p75: 1,
      source: "Industry",
      vintage: "2025",
    },
  },

  // Security
  {
    id: "tech_mttr_vuln",
    name: "Vulnerability MTTR",
    domain: "technology",
    category: "Security",
    unit: "days",
    description: "Time to patch critical vulns",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 60,
      p50: 30,
      p75: 7,
      source: "Industry",
      vintage: "2025",
    },
  },
  {
    id: "tech_code_coverage",
    name: "Code Coverage",
    domain: "technology",
    category: "Quality",
    unit: "percentage",
    description: "Test coverage percentage",
    dependencies: [],
    improvementDirection: "higher_is_better",
    benchmarks: {
      p25: 40,
      p50: 70,
      p75: 85,
      source: "Industry",
      vintage: "2025",
    },
  },

  // Cost
  {
    id: "tech_cloud_cost_per_user",
    name: "Cloud Cost per User",
    domain: "technology",
    category: "Cost",
    unit: "usd",
    description: "Monthly cloud cost per user",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 50,
      p50: 25,
      p75: 10,
      source: "Flexera",
      vintage: "2025",
    },
  },
  {
    id: "tech_maintenance_ratio",
    name: "Maintenance Ratio",
    domain: "technology",
    category: "Cost",
    unit: "percentage",
    description: "Time on maintenance vs new features",
    dependencies: [],
    improvementDirection: "lower_is_better",
    benchmarks: {
      p25: 60,
      p50: 40,
      p75: 20,
      source: "Industry",
      vintage: "2025",
    },
  },
];

// ============================================================================
// Combined Export - All 200+ KPIs
// ============================================================================

export const ALL_STRUCTURAL_KPIS: StructuralKPINode[] = [
  ...SAAS_KPIS,
  ...FINANCE_KPIS,
  ...MANUFACTURING_KPIS,
  ...HEALTHCARE_KPIS,
  ...RETAIL_KPIS,
  ...TECHNOLOGY_KPIS,
];

// ============================================================================
// Extended Persona Value Maps
// ============================================================================

export const EXTENDED_STRUCTURAL_PERSONA_MAPS: StructuralPersonaValueMap[] = [
  {
    persona: "cfo",
    primaryPain: "Working Capital Friction",
    painDescription: "Cash flow visibility and optimization",
    keyKPIs: ["fin_dso", "fin_ccc", "fin_ap_cost", "fin_close_cycle"],
    financialDriver: "fcf_improvement",
    typicalGoals: ["Reduce DSO 10 days", "Improve CCC", "Faster close"],
    communicationPreference: "strategic",
  },
  {
    persona: "cio",
    primaryPain: "Technical Debt",
    painDescription: "Legacy systems and integration burden",
    keyKPIs: [
      "tech_maintenance_ratio",
      "tech_uptime",
      "tech_cloud_cost_per_user",
    ],
    financialDriver: "cost_reduction",
    typicalGoals: ["Reduce maintenance 20%", "99.9% uptime"],
    communicationPreference: "technical",
  },
  {
    persona: "coo",
    primaryPain: "Operational Inefficiency",
    painDescription: "Process variability and throughput",
    keyKPIs: ["mfg_oee", "mfg_throughput", "mfg_cycle_time"],
    financialDriver: "productivity_gain",
    typicalGoals: ["85% OEE", "Reduce cycle time"],
    communicationPreference: "hybrid",
  },
  {
    persona: "vp_sales",
    primaryPain: "Pipeline Volatility",
    painDescription: "Inconsistent pipeline and win rates",
    keyKPIs: ["saas_win_rate", "saas_sales_cycle", "saas_pipeline_coverage"],
    financialDriver: "revenue_uplift",
    typicalGoals: ["30% win rate", "Shorten cycle 20%"],
    communicationPreference: "strategic",
  },
  {
    persona: "vp_ops",
    primaryPain: "Asset Downtime",
    painDescription: "Equipment failures and maintenance",
    keyKPIs: ["mfg_mtbf", "mfg_mttr", "mfg_unplanned_downtime"],
    financialDriver: "productivity_gain",
    typicalGoals: ["Reduce downtime 50%", "Increase MTBF"],
    communicationPreference: "hybrid",
  },
  {
    persona: "vp_engineering",
    primaryPain: "Delivery Speed",
    painDescription: "Slow releases and quality issues",
    keyKPIs: [
      "tech_cycle_time",
      "tech_deploy_frequency",
      "tech_change_failure_rate",
    ],
    financialDriver: "productivity_gain",
    typicalGoals: ["Daily deploys", "<5% failure rate"],
    communicationPreference: "technical",
  },
  {
    persona: "cto",
    primaryPain: "Technical Strategy",
    painDescription: "Architecture and scalability",
    keyKPIs: ["tech_uptime", "tech_lead_time", "tech_code_coverage"],
    financialDriver: "capital_efficiency",
    typicalGoals: ["99.99% uptime", "Modern architecture"],
    communicationPreference: "technical",
  },
  {
    persona: "director_finance",
    primaryPain: "Process Efficiency",
    painDescription: "Manual processes and errors",
    keyKPIs: ["fin_ap_cost", "fin_close_fte", "fin_forecast_accuracy"],
    financialDriver: "cost_reduction",
    typicalGoals: ["Automate 70%", "Reduce close FTEs"],
    communicationPreference: "hybrid",
  },
  {
    persona: "data_analyst",
    primaryPain: "Data Quality",
    painDescription: "Inconsistent and incomplete data",
    keyKPIs: ["fin_forecast_accuracy", "tech_code_coverage"],
    financialDriver: "productivity_gain",
    typicalGoals: ["95% accuracy", "Real-time data"],
    communicationPreference: "technical",
  },
];

// ============================================================================
// Extended Edge Relationships
// ============================================================================

export const EXTENDED_STRUCTURAL_EDGES: StructuralEdge[] = [
  // SaaS edges
  {
    id: "e_churn_nrr",
    sourceId: "saas_logo_churn",
    targetId: "saas_nrr",
    type: "inverse_correlation",
    strength: -0.9,
    description: "Higher churn reduces NRR",
  },
  {
    id: "e_ltv_cac",
    sourceId: "saas_ltv",
    targetId: "saas_ltv_cac_ratio",
    type: "causal_driver",
    strength: 0.8,
    description: "LTV drives ratio",
  },
  {
    id: "e_cac_ratio",
    sourceId: "saas_cac",
    targetId: "saas_ltv_cac_ratio",
    type: "inverse_correlation",
    strength: -0.8,
    description: "CAC reduces ratio",
  },
  {
    id: "e_arpu_ltv",
    sourceId: "saas_arpu",
    targetId: "saas_ltv",
    type: "causal_driver",
    strength: 0.7,
    description: "ARPU increases LTV",
  },
  {
    id: "e_win_revenue",
    sourceId: "saas_win_rate",
    targetId: "saas_arr",
    type: "causal_driver",
    strength: 0.6,
    description: "Win rate drives ARR",
  },

  // Finance edges
  {
    id: "e_dso_ccc",
    sourceId: "fin_dso",
    targetId: "fin_ccc",
    type: "component_of",
    strength: 0.33,
    description: "DSO is component of CCC",
  },
  {
    id: "e_dio_ccc",
    sourceId: "fin_dio",
    targetId: "fin_ccc",
    type: "component_of",
    strength: 0.33,
    description: "DIO is component of CCC",
  },
  {
    id: "e_dpo_ccc",
    sourceId: "fin_dpo",
    targetId: "fin_ccc",
    type: "inverse_correlation",
    strength: -0.33,
    description: "DPO reduces CCC",
  },
  {
    id: "e_ap_close",
    sourceId: "fin_ap_cost",
    targetId: "fin_cost_per_revenue",
    type: "influences",
    strength: 0.3,
    description: "AP cost influences overall",
  },

  // Manufacturing edges
  {
    id: "e_avail_oee",
    sourceId: "mfg_availability",
    targetId: "mfg_oee",
    type: "component_of",
    strength: 0.33,
    description: "Availability component",
  },
  {
    id: "e_perf_oee",
    sourceId: "mfg_performance",
    targetId: "mfg_oee",
    type: "component_of",
    strength: 0.33,
    description: "Performance component",
  },
  {
    id: "e_qual_oee",
    sourceId: "mfg_quality",
    targetId: "mfg_oee",
    type: "component_of",
    strength: 0.33,
    description: "Quality component",
  },
  {
    id: "e_oee_through",
    sourceId: "mfg_oee",
    targetId: "mfg_throughput",
    type: "causal_driver",
    strength: 0.9,
    description: "OEE drives throughput",
  },
  {
    id: "e_mtbf_avail",
    sourceId: "mfg_mtbf",
    targetId: "mfg_availability",
    type: "causal_driver",
    strength: 0.7,
    description: "MTBF improves availability",
  },
  {
    id: "e_mttr_avail",
    sourceId: "mfg_mttr",
    targetId: "mfg_availability",
    type: "inverse_correlation",
    strength: -0.6,
    description: "MTTR reduces availability",
  },

  // Technology edges
  {
    id: "e_deploy_cycle",
    sourceId: "tech_deploy_frequency",
    targetId: "tech_cycle_time",
    type: "inverse_correlation",
    strength: -0.7,
    description: "More deploys = shorter cycles",
  },
  {
    id: "e_coverage_failure",
    sourceId: "tech_code_coverage",
    targetId: "tech_change_failure_rate",
    type: "inverse_correlation",
    strength: -0.5,
    description: "Coverage reduces failures",
  },

  // Healthcare edges
  {
    id: "e_clean_denial",
    sourceId: "hc_clean_claim_rate",
    targetId: "hc_denial_rate",
    type: "inverse_correlation",
    strength: -0.8,
    description: "Clean claims reduce denials",
  },
  {
    id: "e_denial_ar",
    sourceId: "hc_denial_rate",
    targetId: "hc_days_in_ar",
    type: "causal_driver",
    strength: 0.6,
    description: "Denials increase A/R days",
  },

  // Retail edges
  {
    id: "e_shrink_margin",
    sourceId: "ret_shrinkage",
    targetId: "ret_gross_margin",
    type: "inverse_correlation",
    strength: -0.4,
    description: "Shrinkage reduces margin",
  },
  {
    id: "e_turns_gmroi",
    sourceId: "ret_inventory_turns",
    targetId: "ret_gmroi",
    type: "causal_driver",
    strength: 0.7,
    description: "Turns improve GMROI",
  },
];

// ============================================================================
// Initial Formula Registry (Phase 1 Expansion)
// ============================================================================

export const INITIAL_FORMULA_REGISTRY: FormulaRegistry[] = [
  // SaaS Formulas
  {
    formula_id: "f_saas_mrr",
    formula_name: "Monthly Recurring Revenue",
    output_kpi: "saas_mrr",
    input_kpis: ["saas_arr"],
    functional_form: "ratio",
    formula: "arr / 12",
    directionality: { saas_arr: "higher_is_better" },
    domain: "saas",
    required_units: ["usd"],
    validation_constraints: {
      output_range: [83333, 1666667],
      logical_checks: ["arr >= 0"],
    },
    dependencies: [],
    complexity_score: 1,
  },
  {
    formula_id: "f_saas_nrr",
    formula_name: "Net Revenue Retention",
    output_kpi: "saas_nrr",
    input_kpis: ["saas_logo_churn", "saas_expansion_revenue"],
    functional_form: "ratio",
    formula: "(starting_arr + expansion - churn) / starting_arr * 100",
    directionality: {
      saas_logo_churn: "lower_is_better",
      saas_expansion_revenue: "higher_is_better",
    },
    domain: "saas",
    required_units: ["percentage", "usd"],
    validation_constraints: {
      output_range: [97, 130],
      logical_checks: ["starting_arr > 0", "expansion >= 0", "churn >= 0"],
    },
    dependencies: [],
    complexity_score: 2,
  },
  {
    formula_id: "f_saas_ltv_cac",
    formula_name: "LTV:CAC Ratio",
    output_kpi: "saas_ltv_cac_ratio",
    input_kpis: ["saas_ltv", "saas_cac"],
    functional_form: "ratio",
    formula: "ltv / cac",
    directionality: {
      saas_ltv: "higher_is_better",
      saas_cac: "lower_is_better",
    },
    domain: "saas",
    required_units: ["usd", "usd"],
    validation_constraints: {
      output_range: [2, 7],
      logical_checks: ["ltv > 0", "cac > 0"],
    },
    dependencies: [],
    complexity_score: 1,
  },

  // Finance Formulas
  {
    formula_id: "f_fin_ccc",
    formula_name: "Cash Conversion Cycle",
    output_kpi: "fin_ccc",
    input_kpis: ["fin_dso", "fin_dio", "fin_dpo"],
    functional_form: "difference",
    formula: "dso + dio - dpo",
    directionality: {
      fin_dso: "lower_is_better",
      fin_dio: "lower_is_better",
      fin_dpo: "higher_is_better",
    },
    domain: "finance",
    required_units: ["days", "days", "days"],
    validation_constraints: {
      output_range: [20, 60],
      logical_checks: ["dso >= 0", "dio >= 0", "dpo >= 0"],
    },
    dependencies: [],
    complexity_score: 1,
  },

  // Manufacturing Formulas
  {
    formula_id: "f_mfg_oee",
    formula_name: "Overall Equipment Effectiveness",
    output_kpi: "mfg_oee",
    input_kpis: ["mfg_availability", "mfg_performance", "mfg_quality"],
    functional_form: "product",
    formula: "availability * performance * quality",
    directionality: {
      mfg_availability: "higher_is_better",
      mfg_performance: "higher_is_better",
      mfg_quality: "higher_is_better",
    },
    domain: "manufacturing",
    required_units: ["percentage", "percentage", "percentage"],
    validation_constraints: {
      output_range: [45, 95],
      logical_checks: ["availability <= 1", "performance <= 1", "quality <= 1"],
    },
    dependencies: [],
    complexity_score: 2,
  },
  {
    formula_id: "f_mfg_throughput",
    formula_name: "Manufacturing Throughput",
    output_kpi: "mfg_throughput",
    input_kpis: ["mfg_oee"],
    functional_form: "product",
    formula: "theoretical_max * oee",
    directionality: { mfg_oee: "higher_is_better" },
    domain: "manufacturing",
    required_units: ["units_per_hour", "percentage"],
    validation_constraints: {
      output_range: [100, 200],
      logical_checks: ["oee <= 1"],
    },
    dependencies: ["f_mfg_oee"],
    complexity_score: 2,
  },
];

console.log(`Loaded ${ALL_STRUCTURAL_KPIS.length} Structural KPI nodes`);