/**
 * Artifact Engine Service
 * Core service for managing and generating ValueOS artifacts
 *
 * This service orchestrates artifact generation, versioning, branding, and distribution
 */

import { EventEmitter } from "events";

import { createClient } from "@supabase/supabase-js";

import {
  Artifact,
  ArtifactFormat,
  ArtifactGenerationRequest,
  ArtifactGenerationResult,
  ArtifactStorageMetadata,
  ArtifactTemplate,
  ArtifactType,
  ArtifactVersion,
  AuditEvent,
  AuditEventType,
  BrandingProfile,
  CreateArtifact,
  DistributionRecord,
  DistributionStatus,
  RetentionPolicy,
  ScheduledReport,
  UpdateArtifact,
} from "../types/artifact";
import { Database } from "../types/database";

// ============================================================================
// Configuration
// ============================================================================

export interface ArtifactEngineConfig {
  supabaseUrl: string;
  supabaseAnonKey: string;
  storageBucket: string;
  defaultRetentionDays: number;
  maxArtifactSizeMB: number;
  generationTimeoutMs: number;
}

// ============================================================================
// Progress Events
// ============================================================================

export interface ArtifactProgress {
  status: "preparing" | "generating" | "versioning" | "storing" | "distributing" | "complete" | "error";
  progress: number;
  message?: string;
  artifactId?: string;
  versionId?: string;
}

// ============================================================================
// Artifact Engine Service
// ============================================================================

export class ArtifactEngine extends EventEmitter {
  private supabase: ReturnType<typeof createClient<Database>>;
  private config: ArtifactEngineConfig;
  private templates: Map<string, ArtifactTemplate> = new Map();
  private brandingProfiles: Map<string, BrandingProfile> = new Map();

  constructor(config: ArtifactEngineConfig) {
    super();
    this.config = config;
    this.supabase = createClient<Database>(config.supabaseUrl, config.supabaseAnonKey);

    // Initialize with default templates
    this.initializeDefaultTemplates();
  }

  // ============================================================================
  // Initialization
  // ============================================================================

  private initializeDefaultTemplates(): void {
    // Executive Summary Template
    this.templates.set("executive_summary", {
      id: "template-executive-summary-v1",
      name: "Executive Summary",
      type: "executive_summary",
      format: "pdf",
      version: "1.0.0",
      structure: {
        sections: [
          { id: "header", type: "title", content: "Executive Summary" },
          { id: "overview", type: "text", content: "Value Overview" },
          { id: "key_metrics", type: "metrics", content: "Key Performance Indicators" },
          { id: "recommendations", type: "list", content: "Recommendations" },
          { id: "footer", type: "metadata", content: "Generated by ValueOS" },
        ],
      },
      metadata: {
        description: "High-level value overview for executives",
        category: "executive",
        tags: ["summary", "executive", "high-level"],
        isDefault: true,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });

    // CFO Brief Template
    this.templates.set("cfo_brief", {
      id: "template-cfo-brief-v1",
      name: "CFO ROI Brief",
      type: "cfo_brief",
      format: "pdf",
      version: "1.0.0",
      structure: {
        sections: [
          { id: "header", type: "title", content: "ROI Analysis" },
          { id: "financials", type: "table", content: "Financial Projections" },
          { id: "risk_analysis", type: "text", content: "Risk Analysis" },
          { id: "payback_period", type: "metric", content: "Payback Period" },
          { id: "assumptions", type: "list", content: "Key Assumptions" },
        ],
      },
      metadata: {
        description: "Financial justification for CFO review",
        category: "financial",
        tags: ["roi", "financial", "cfo"],
        isDefault: true,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });

    // Board Deck Template
    this.templates.set("board_deck", {
      id: "template-board-deck-v1",
      name: "Board Deck",
      type: "board_deck",
      format: "pptx",
      version: "1.0.0",
      structure: {
        slides: [
          { id: "title", layout: "title", content: "Value Analysis" },
          { id: "executive_summary", layout: "content", content: "Executive Summary" },
          { id: "financial_impact", layout: "chart", content: "Financial Impact" },
          { id: "strategic_implications", layout: "content", content: "Strategic Implications" },
          { id: "recommendations", layout: "content", content: "Recommendations" },
          { id: "next_steps", layout: "content", content: "Next Steps" },
        ],
      },
      metadata: {
        description: "Board presentation deck",
        category: "governance",
        tags: ["board", "presentation", "strategic"],
        isDefault: true,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
  }

  // ============================================================================
  // Artifact Management
  // ============================================================================

  /**
   * Create a new artifact
   */
  async createArtifact(input: CreateArtifact): Promise<Artifact> {
    const artifact: Artifact = {
      id: crypto.randomUUID(),
      ...input,
      currentVersion: "1.0.0",
      versionHistory: ["1.0.0"],
      status: input.status || "draft",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const { data, error } = await this.supabase
      .from("workflow_artifacts")
      .insert(artifact)
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to create artifact: ${error.message}`);
    }

    // Emit event
    this.emit("artifact_created", { artifactId: artifact.id });

    return data;
  }

  /**
   * Update an artifact
   */
  async updateArtifact(artifactId: string, updates: UpdateArtifact): Promise<Artifact> {
    const updatesWithTimestamp = {
      ...updates,
      updatedAt: new Date().toISOString(),
    };

    const { data, error } = await this.supabase
      .from("workflow_artifacts")
      .update(updatesWithTimestamp)
      .eq("id", artifactId)
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to update artifact: ${error.message}`);
    }

    // Emit event
    this.emit("artifact_updated", { artifactId });

    return data;
  }

  /**
   * Get an artifact by ID
   */
  async getArtifact(artifactId: string): Promise<Artifact | null> {
    const { data, error } = await this.supabase
      .from("workflow_artifacts")
      .select()
      .eq("id", artifactId)
      .single();

    if (error) {
      if (error.code === "PGRST116") {
        return null; // Not found
      }
      throw new Error(`Failed to get artifact: ${error.message}`);
    }

    return data;
  }

  /**
   * List artifacts with filters
   */
  async listArtifacts(filters: {
    organizationId?: string;
    tenantId?: string;
    type?: ArtifactType;
    status?: Artifact["status"];
    createdBy?: string;
    limit?: number;
    offset?: number;
  }): Promise<Artifact[]> {
    let query = this.supabase.from("workflow_artifacts").select();

    if (filters.organizationId) {
      query = query.eq("organizationId", filters.organizationId);
    }
    if (filters.tenantId) {
      query = query.eq("tenantId", filters.tenantId);
    }
    if (filters.type) {
      query = query.eq("type", filters.type);
    }
    if (filters.status) {
      query = query.eq("status", filters.status);
    }
    if (filters.createdBy) {
      query = query.eq("createdBy", filters.createdBy);
    }

    if (filters.limit) {
      query = query.limit(filters.limit);
    }
    if (filters.offset) {
      query = query.range(filters.offset, filters.offset + (filters.limit || 10) - 1);
    }

    const { data, error } = await query;

    if (error) {
      throw new Error(`Failed to list artifacts: ${error.message}`);
    }

    return data || [];
  }

  // ============================================================================
  // Artifact Generation
  // ============================================================================

  /**
   * Generate an artifact based on request
   */
  async generateArtifact(
    request: ArtifactGenerationRequest,
    onProgress?: (progress: ArtifactProgress) => void
  ): Promise<ArtifactGenerationResult> {
    try {
      onProgress?.({
        status: "preparing",
        progress: 10,
        message: "Preparing artifact generation...",
      });

      // Get value case data
      const valueCase = await this.getValueCaseData(request.valueCaseId);
      if (!valueCase) {
        throw new Error(`Value case ${request.valueCaseId} not found`);
      }

      // Get branding profile
      let brandingProfile: BrandingProfile | undefined;
      if (request.brandingProfileId) {
        brandingProfile = await this.getBrandingProfile(request.brandingProfileId);
      }

      // Get template
      const template = this.templates.get(request.artifactType);
      if (!template) {
        throw new Error(`No template found for artifact type: ${request.artifactType}`);
      }

      onProgress?.({
        status: "generating",
        progress: 40,
        message: "Generating artifact content...",
      });

      // Generate artifact data
      const artifactData = await this.generateArtifactData(
        template,
        valueCase,
        brandingProfile
      );

      onProgress?.({
        status: "versioning",
        progress: 60,
        message: "Creating version...",
      });

      // Create artifact
      const artifact = await this.createArtifact({
        organizationId: valueCase.organizationId,
        tenantId: valueCase.tenantId,
        type: request.artifactType,
        format: request.format,
        name: `${template.name} - ${valueCase.companyName}`,
        description: template.metadata.description,
        valueCaseId: request.valueCaseId,
        brandingProfileId: request.brandingProfileId,
        distributionOptions: request.distributionOptions,
        status: "generating",
        createdBy: valueCase.createdBy,
      });

      // Create version
      const version = await this.createArtifactVersion(artifact.id, request.format, artifactData, {
        generatedBy: valueCase.createdBy,
        dataHash: this.generateDataHash(artifactData),
        sourceDataVersion: valueCase.version,
        assumptions: valueCase.assumptions,
      });

      onProgress?.({
        status: "storing",
        progress: 80,
        message: "Storing artifact...",
        artifactId: artifact.id,
        versionId: version.id,
      });

      // Store artifact
      const storageMetadata = await this.storeArtifact(
        artifact.id,
        version.id,
        request.format,
        artifactData
      );

      // Update artifact status
      await this.updateArtifact(artifact.id, { status: "ready" });

      onProgress?.({
        status: "distributing",
        progress: 90,
        message: "Distributing artifact...",
      });

      // Distribute if requested
      if (request.distributionOptions) {
        await this.distributeArtifact(artifact.id, version.id, request.distributionOptions);
      }

      onProgress?.({
        status: "complete",
        progress: 100,
        message: "Artifact generation complete!",
        artifactId: artifact.id,
        versionId: version.id,
      });

      // Emit event
      this.emit("artifact_generated", {
        artifactId: artifact.id,
        versionId: version.id,
        format: request.format,
      });

      return {
        success: true,
        artifactId: artifact.id,
        versionId: version.id,
        format: request.format,
        data: artifactData,
        metadata: {
          generatedAt: new Date().toISOString(),
          generationTimeMs: Date.now() - Date.now(), // Placeholder
          dataHash: version.metadata.dataHash,
        },
      };
    } catch (error) {
      onProgress?.({
        status: "error",
        progress: 0,
        message: error instanceof Error ? error.message : "Generation failed",
      });

      return {
        success: false,
        errors: [error instanceof Error ? error.message : "Unknown error"],
      };
    }
  }

  // ============================================================================
  // Version Management
  // ============================================================================

  /**
   * Create a new version of an artifact
   */
  async createArtifactVersion(
    artifactId: string,
    format: ArtifactFormat,
    data: unknown,
    metadata: {
      generatedBy: string;
      dataHash: string;
      sourceDataVersion?: string;
      assumptions?: unknown[];
    }
  ): Promise<ArtifactVersion> {
    const artifact = await this.getArtifact(artifactId);
    if (!artifact) {
      throw new Error(`Artifact ${artifactId} not found`);
    }

    // Increment version (simple semantic versioning)
    const currentVersion = artifact.currentVersion;
    const [major, minor, patch] = currentVersion.split(".").map(Number);
    const newVersion = `${major}.${minor}.${patch + 1}`;

    const version: ArtifactVersion = {
      id: crypto.randomUUID(),
      artifactId,
      version: newVersion,
      format,
      data,
      metadata: {
        generatedAt: new Date().toISOString(),
        ...metadata,
      },
      createdAt: new Date().toISOString(),
    };

    const { data: inserted, error } = await this.supabase
      .from("artifact_versions")
      .insert(version)
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to create version: ${error.message}`);
    }

    // Update artifact with new version
    await this.updateArtifact(artifactId, {
      currentVersion: newVersion,
      versionHistory: [...artifact.versionHistory, newVersion],
    });

    // Emit event
    this.emit("artifact_versioned", { artifactId, versionId: version.id, version: newVersion });

    return inserted;
  }

  /**
   * Get version history for an artifact
   */
  async getVersionHistory(artifactId: string): Promise<ArtifactVersion[]> {
    const { data, error } = await this.supabase
      .from("artifact_versions")
      .select()
      .eq("artifactId", artifactId)
      .order("createdAt", { ascending: false });

    if (error) {
      throw new Error(`Failed to get version history: ${error.message}`);
    }

    return data || [];
  }

  /**
   * Get a specific version
   */
  async getVersion(artifactId: string, version: string): Promise<ArtifactVersion | null> {
    const { data, error } = await this.supabase
      .from("artifact_versions")
      .select()
      .eq("artifactId", artifactId)
      .eq("version", version)
      .single();

    if (error) {
      if (error.code === "PGRST116") {
        return null;
      }
      throw new Error(`Failed to get version: ${error.message}`);
    }

    return data;
  }

  // ============================================================================
  // Branding Management
  // ============================================================================

  /**
   * Get branding profile
   */
  async getBrandingProfile(profileId: string): Promise<BrandingProfile | null> {
    // Check cache first
    if (this.brandingProfiles.has(profileId)) {
      return this.brandingProfiles.get(profileId)!;
    }

    const { data, error } = await this.supabase
      .from("branding_profiles")
      .select()
      .eq("id", profileId)
      .single();

    if (error) {
      if (error.code === "PGRST116") {
        return null;
      }
      throw new Error(`Failed to get branding profile: ${error.message}`);
    }

    // Cache the profile
    this.brandingProfiles.set(profileId, data);

    return data;
  }

  /**
   * Create branding profile
   */
  async createBrandingProfile(profile: Omit<BrandingProfile, "id" | "createdAt" | "updatedAt">): Promise<BrandingProfile> {
    const newProfile: BrandingProfile = {
      id: crypto.randomUUID(),
      ...profile,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const { data, error } = await this.supabase
      .from("branding_profiles")
      .insert(newProfile)
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to create branding profile: ${error.message}`);
    }

    // Cache the profile
    this.brandingProfiles.set(newProfile.id, data);

    return data;
  }

  // ============================================================================
  // Template Management
  // ============================================================================

  /**
   * Get template
   */
  getTemplate(type: ArtifactType): ArtifactTemplate | undefined {
    return this.templates.get(type);
  }

  /**
   * List available templates
   */
  listTemplates(): ArtifactTemplate[] {
    return Array.from(this.templates.values());
  }

  /**
   * Register custom template
   */
  registerTemplate(template: ArtifactTemplate): void {
    this.templates.set(template.type, template);
  }

  // ============================================================================
  // Storage Management
  // ============================================================================

  /**
   * Store artifact in storage
   */
  async storeArtifact(
    artifactId: string,
    versionId: string,
    format: ArtifactFormat,
    data: unknown
  ): Promise<ArtifactStorageMetadata> {
    // Convert data to appropriate format
    let content: Blob;
    let mimeType: string;

    switch (format) {
      case "pdf":
        content = new Blob([JSON.stringify(data)], { type: "application/pdf" });
        mimeType = "application/pdf";
        break;
      case "pptx":
        content = new Blob([JSON.stringify(data)], { type: "application/vnd.openxmlformats-officedocument.presentationml.presentation" });
        mimeType = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        break;
      case "html":
        content = new Blob([JSON.stringify(data)], { type: "text/html" });
        mimeType = "text/html";
        break;
      case "csv":
        content = new Blob([JSON.stringify(data)], { type: "text/csv" });
        mimeType = "text/csv";
        break;
      case "json":
        content = new Blob([JSON.stringify(data)], { type: "application/json" });
        mimeType = "application/json";
        break;
      default:
        throw new Error(`Unsupported format: ${format}`);
    }

    const sizeBytes = content.size;
    const checksum = await this.generateChecksum(content);

    // Upload to storage
    const filePath = `artifacts/${artifactId}/${versionId}.${format}`;
    const { error } = await this.supabase.storage
      .from(this.config.storageBucket)
      .upload(filePath, content, {
        contentType: mimeType,
        upsert: true,
      });

    if (error) {
      throw new Error(`Failed to store artifact: ${error.message}`);
    }

    const storageMetadata: ArtifactStorageMetadata = {
      artifactId,
      versionId,
      storagePath: filePath,
      format,
      sizeBytes,
      mimeType,
      checksum,
      uploadedAt: new Date().toISOString(),
    };

    // Store metadata
    const { error: metadataError } = await this.supabase
      .from("artifact_storage_metadata")
      .insert(storageMetadata);

    if (metadataError) {
      throw new Error(`Failed to store metadata: ${metadataError.message}`);
    }

    return storageMetadata;
  }

  /**
   * Retrieve artifact from storage
   */
  async retrieveArtifact(artifactId: string, versionId: string, format: ArtifactFormat): Promise<Blob> {
    const filePath = `artifacts/${artifactId}/${versionId}.${format}`;

    const { data, error } = await this.supabase.storage
      .from(this.config.storageBucket)
      .download(filePath);

    if (error) {
      throw new Error(`Failed to retrieve artifact: ${error.message}`);
    }

    return data;
  }

  // ============================================================================
  // Distribution
  // ============================================================================

  /**
   * Distribute artifact to recipients
   */
  async distributeArtifact(
    artifactId: string,
    versionId: string,
    options: {
      email?: string[];
      webhooks?: string[];
      retentionDays?: number;
    }
  ): Promise<DistributionRecord[]> {
    const records: DistributionRecord[] = [];

    // Distribute via email
    if (options.email && options.email.length > 0) {
      for (const email of options.email) {
        const record = await this.distributeViaEmail(artifactId, versionId, email);
        records.push(record);
      }
    }

    // Distribute via webhooks
    if (options.webhooks && options.webhooks.length > 0) {
      for (const webhook of options.webhooks) {
        const record = await this.distributeViaWebhook(artifactId, versionId, webhook);
        records.push(record);
      }
    }

    return records;
  }

  /**
   * Distribute via email
   */
  async distributeViaEmail(
    artifactId: string,
    versionId: string,
    email: string
  ): Promise<DistributionRecord> {
    const record: DistributionRecord = {
      id: crypto.randomUUID(),
      artifactId,
      versionId,
      channel: "email",
      recipient: email,
      status: "pending",
      attempts: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const { data, error } = await this.supabase
      .from("artifact_distributions")
      .insert(record)
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to create distribution record: ${error.message}`);
    }

    // In a real implementation, this would trigger an email service
    // For now, we'll just mark it as delivered
    await this.updateDistributionStatus(record.id, "delivered");

    return data;
  }

  /**
   * Distribute via webhook
   */
  async distributeViaWebhook(
    artifactId: string,
    versionId: string,
    webhookUrl: string
  ): Promise<DistributionRecord> {
    const record: DistributionRecord = {
      id: crypto.randomUUID(),
      artifactId,
      versionId,
      channel: "webhook",
      recipient: webhookUrl,
      status: "pending",
      attempts: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const { data, error } = await this.supabase
      .from("artifact_distributions")
      .insert(record)
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to create distribution record: ${error.message}`);
    }

    // In a real implementation, this would trigger a webhook call
    // For now, we'll just mark it as delivered
    await this.updateDistributionStatus(record.id, "delivered");

    return data;
  }

  /**
   * Update distribution status
   */
  async updateDistributionStatus(recordId: string, status: DistributionStatus, error?: string): Promise<DistributionRecord> {
    const { data, error: updateError } = await this.supabase
      .from("artifact_distributions")
      .update({
        status,
        error,
        updatedAt: new Date().toISOString(),
      })
      .eq("id", recordId)
      .select()
      .single();

    if (updateError) {
      throw new Error(`Failed to update distribution status: ${updateError.message}`);
    }

    return data;
  }

  // ============================================================================
  // Audit Logging
  // ============================================================================

  /**
   * Log audit event
   */
  async logAuditEvent(
    artifactId: string,
    eventType: AuditEventType,
    userId: string,
    metadata?: Record<string, unknown>
  ): Promise<AuditEvent> {
    const artifact = await this.getArtifact(artifactId);
    if (!artifact) {
      throw new Error(`Artifact ${artifactId} not found`);
    }

    const event: AuditEvent = {
      id: crypto.randomUUID(),
      artifactId,
      organizationId: artifact.organizationId,
      tenantId: artifact.tenantId,
      eventType,
      userId,
      metadata,
      createdAt: new Date().toISOString(),
    };

    const { data, error } = await this.supabase
      .from("artifact_audit_events")
      .insert(event)
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to log audit event: ${error.message}`);
    }

    return data;
  }

  /**
   * Get audit trail for artifact
   */
  async getAuditTrail(artifactId: string): Promise<AuditEvent[]> {
    const { data, error } = await this.supabase
      .from("artifact_audit_events")
      .select()
      .eq("artifactId", artifactId)
      .order("createdAt", { ascending: true });

    if (error) {
      throw new Error(`Failed to get audit trail: ${error.message}`);
    }

    return data || [];
  }

  // ============================================================================
  // Retention Management
  // ============================================================================

  /**
   * Apply retention policies
   */
  async applyRetentionPolicy(policy: RetentionPolicy): Promise<void> {
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - policy.rules.archiveAfterDays);

    // Get artifacts to archive
    const { data: artifacts, error } = await this.supabase
      .from("workflow_artifacts")
      .select()
      .eq("organizationId", policy.organizationId)
      .eq("status", "ready")
      .lt("createdAt", cutoffDate.toISOString());

    if (error) {
      throw new Error(`Failed to get artifacts for retention: ${error.message}`);
    }

    // Archive artifacts
    for (const artifact of artifacts || []) {
      await this.updateArtifact(artifact.id, {
        status: "archived",
        archivedAt: new Date().toISOString(),
      });
    }

    // Clean up old versions
    if (policy.rules.keepVersions > 0) {
      await this.cleanupOldVersions(policy.organizationId, policy.rules.keepVersions);
    }
  }

  /**
   * Cleanup old versions
   */
  async cleanupOldVersions(organizationId: string, keepVersions: number): Promise<void> {
    const { data: artifacts, error } = await this.supabase
      .from("workflow_artifacts")
      .select()
      .eq("organizationId", organizationId);

    if (error) {
      throw new Error(`Failed to get artifacts: ${error.message}`);
    }

    for (const artifact of artifacts || []) {
      const versions = await this.getVersionHistory(artifact.id);

      if (versions.length > keepVersions) {
        const versionsToDelete = versions.slice(keepVersions);

        for (const version of versionsToDelete) {
          // Delete from storage
          const filePath = `artifacts/${artifact.id}/${version.id}.${version.format}`;
          await this.supabase.storage
            .from(this.config.storageBucket)
            .remove([filePath]);

          // Delete version record
          await this.supabase
            .from("artifact_versions")
            .delete()
            .eq("id", version.id);
        }
      }
    }
  }

  // ============================================================================
  // Scheduled Reports
  // ============================================================================

  /**
   * Create scheduled report
   */
  async createScheduledReport(report: Omit<ScheduledReport, "id" | "createdAt" | "updatedAt" | "nextRunAt">): Promise<ScheduledReport> {
    const nextRunAt = this.calculateNextRun(report.schedule);

    const newReport: ScheduledReport = {
      id: crypto.randomUUID(),
      ...report,
      nextRunAt,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const { data, error } = await this.supabase
      .from("scheduled_reports")
      .insert(newReport)
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to create scheduled report: ${error.message}`);
    }

    return data;
  }

  /**
   * Run scheduled reports
   */
  async runScheduledReports(): Promise<void> {
    const now = new Date().toISOString();

    const { data: reports, error } = await this.supabase
      .from("scheduled_reports")
      .select()
      .eq("isActive", true)
      .lt("nextRunAt", now);

    if (error) {
      throw new Error(`Failed to get scheduled reports: ${error.message}`);
    }

    for (const report of reports || []) {
      try {
        // Generate artifact
        const result = await this.generateArtifact({
          artifactType: report.artifactType,
          valueCaseId: report.filters?.valueCaseId,
          brandingProfileId: report.brandingProfileId,
          format: report.format,
          distributionOptions: {
            email: report.recipients,
            retentionDays: report.retentionPolicy.archiveAfterDays,
          },
        });

        if (result.success) {
          // Update last run and next run
          const nextRunAt = this.calculateNextRun(report.schedule);
          await this.supabase
            .from("scheduled_reports")
            .update({
              lastRunAt: now,
              nextRunAt,
              updatedAt: new Date().toISOString(),
            })
            .eq("id", report.id);
        }
      } catch (error) {
        console.error(`Failed to run scheduled report ${report.id}:`, error);
      }
    }
  }

  // ============================================================================
  // Helper Methods
  // ============================================================================

  private async getValueCaseData(valueCaseId: string): Promise<unknown> {
    const { data, error } = await this.supabase
      .from("value_cases")
      .select()
      .eq("id", valueCaseId)
      .single();

    if (error) {
      return null;
    }

    return data;
  }

  private async generateArtifactData(
    template: ArtifactTemplate,
    valueCase: unknown,
    brandingProfile?: BrandingProfile
  ): Promise<unknown> {
    // In a real implementation, this would use a template engine
    // For now, we'll return a simplified structure
    return {
      template: template.name,
      type: template.type,
      format: template.format,
      valueCase: {
        id: valueCase.id,
        companyName: valueCase.companyName,
        businessCase: valueCase.business_case,
      },
      branding: brandingProfile
        ? {
            companyName: brandingProfile.companyName,
            primaryColor: brandingProfile.primaryColor,
            logoUrl: brandingProfile.logoUrl,
          }
        : null,
      generatedAt: new Date().toISOString(),
    };
  }

  private generateDataHash(data: unknown): string {
    const str = JSON.stringify(data);
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash; // Convert to 32-bit integer
    }
    return hash.toString(16);
  }

  private async generateChecksum(blob: Blob): Promise<string> {
    const arrayBuffer = await blob.arrayBuffer();
    const hashBuffer = await crypto.subtle.digest("SHA-256", arrayBuffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, "0")).join("");
  }

  private calculateNextRun(schedule: ScheduledReport["schedule"]): string {
    const now = new Date();
    const nextRun = new Date(now);

    switch (schedule.frequency) {
      case "daily":
        nextRun.setDate(nextRun.getDate() + 1);
        break;
      case "weekly":
        nextRun.setDate(nextRun.getDate() + 7);
        break;
      case "monthly":
        nextRun.setMonth(nextRun.getMonth() + 1);
        break;
      case "quarterly":
        nextRun.setMonth(nextRun.getMonth() + 3);
        break;
    }

    // Set time
    const [hours, minutes] = schedule.time.split(":").map(Number);
    nextRun.setHours(hours, minutes, 0, 0);

    return nextRun.toISOString();
  }
}

// ============================================================================
// Singleton Instance
// ============================================================================

let artifactEngineInstance: ArtifactEngine | null = null;

export function getArtifactEngine(config?: ArtifactEngineConfig): ArtifactEngine {
  if (!artifactEngineInstance) {
    if (!config) {
      throw new Error("ArtifactEngine config is required for initialization");
    }
    artifactEngineInstance = new ArtifactEngine(config);
  }
  return artifactEngineInstance;
}

export function resetArtifactEngine(): void {
  artifactEngineInstance = null;
}

// Default export
export default ArtifactEngine;
