/**
 * PDF Template Service
 * Handles PDF generation with templates and branding
 *
 * This service provides template-driven PDF generation with organization branding
 */

import { ArtifactTemplate, ArtifactType, BrandingProfile } from "../types/artifact";

// ============================================================================
// PDF Template Service
// ============================================================================

export interface PDFTemplateConfig {
  defaultFont: string;
  defaultFontSize: number;
  defaultMargins: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
  maxImageSizeMB: number;
}

export interface PDFGenerationOptions {
  templateId?: string;
  brandingProfile?: BrandingProfile;
  includePageNumbers?: boolean;
  includeTableOfContents?: boolean;
  compress?: boolean;
  quality?: "low" | "medium" | "high";
}

export interface PDFContent {
  title: string;
  sections: PDFSection[];
  metadata?: Record<string, any>;
}

export interface PDFSection {
  id: string;
  type: "title" | "text" | "table" | "chart" | "list" | "metadata";
  title?: string;
  content: any;
  style?: PDFStyle;
}

export interface PDFStyle {
  fontSize?: number;
  fontWeight?: "normal" | "bold";
  color?: string;
  backgroundColor?: string;
  alignment?: "left" | "center" | "right";
  margin?: {
    top?: number;
    right?: number;
    bottom?: number;
    left?: number;
  };
}

export interface PDFBranding {
  logo?: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  fontFamily: string;
  companyName: string;
  tagline?: string;
}

// ============================================================================
// PDF Template Service
// ============================================================================

export class PDFTemplateService {
  private config: PDFTemplateConfig;
  private templates: Map<string, ArtifactTemplate> = new Map();

  constructor(config?: Partial<PDFTemplateConfig>) {
    this.config = {
      defaultFont: "Helvetica",
      defaultFontSize: 12,
      defaultMargins: {
        top: 20,
        right: 20,
        bottom: 20,
        left: 20,
      },
      maxImageSizeMB: 5,
      ...config,
    };

    this.initializeDefaultTemplates();
  }

  // ============================================================================
  // Template Management
  // ============================================================================

  private initializeDefaultTemplates(): void {
    // Executive Summary Template
    this.templates.set("executive_summary", {
      id: "template-executive-summary-v1",
      name: "Executive Summary",
      type: "executive_summary",
      format: "pdf",
      version: "1.0.0",
      structure: {
        sections: [
          {
            id: "header",
            type: "title",
            content: "Executive Summary",
            style: {
              fontSize: 24,
              fontWeight: "bold",
              alignment: "center",
              margin: { top: 0, right: 0, bottom: 20, left: 0 },
            },
          },
          {
            id: "overview",
            type: "text",
            title: "Overview",
            content: "",
            style: {
              fontSize: 12,
              margin: { top: 10, right: 0, bottom: 10, left: 0 },
            },
          },
          {
            id: "key_metrics",
            type: "table",
            title: "Key Performance Indicators",
            content: [],
            style: {
              fontSize: 11,
              margin: { top: 15, right: 0, bottom: 15, left: 0 },
            },
          },
          {
            id: "recommendations",
            type: "list",
            title: "Recommendations",
            content: [],
            style: {
              fontSize: 12,
              margin: { top: 15, right: 0, bottom: 15, left: 0 },
            },
          },
          {
            id: "footer",
            type: "metadata",
            content: "Generated by ValueOS",
            style: {
              fontSize: 10,
              alignment: "center",
              color: "#666666",
              margin: { top: 20, right: 0, bottom: 0, left: 0 },
            },
          },
        ],
      },
      metadata: {
        description: "High-level value overview for executives",
        category: "executive",
        tags: ["summary", "executive", "high-level"],
        isDefault: true,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });

    // CFO Brief Template
    this.templates.set("cfo_brief", {
      id: "template-cfo-brief-v1",
      name: "CFO ROI Brief",
      type: "cfo_brief",
      format: "pdf",
      version: "1.0.0",
      structure: {
        sections: [
          {
            id: "header",
            type: "title",
            content: "ROI Analysis",
            style: {
              fontSize: 24,
              fontWeight: "bold",
              alignment: "center",
              margin: { top: 0, right: 0, bottom: 20, left: 0 },
            },
          },
          {
            id: "financials",
            type: "table",
            title: "Financial Projections",
            content: [],
            style: {
              fontSize: 11,
              margin: { top: 15, right: 0, bottom: 15, left: 0 },
            },
          },
          {
            id: "risk_analysis",
            type: "text",
            title: "Risk Analysis",
            content: "",
            style: {
              fontSize: 12,
              margin: { top: 15, right: 0, bottom: 15, left: 0 },
            },
          },
          {
            id: "payback_period",
            type: "table",
            title: "Payback Period",
            content: [],
            style: {
              fontSize: 11,
              margin: { top: 15, right: 0, bottom: 15, left: 0 },
            },
          },
          {
            id: "assumptions",
            type: "list",
            title: "Key Assumptions",
            content: [],
            style: {
              fontSize: 12,
              margin: { top: 15, right: 0, bottom: 15, left: 0 },
            },
          },
        ],
      },
      metadata: {
        description: "Financial justification for CFO review",
        category: "financial",
        tags: ["roi", "financial", "cfo"],
        isDefault: true,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });

    // Board Deck Template
    this.templates.set("board_deck", {
      id: "template-board-deck-v1",
      name: "Board Deck",
      type: "board_deck",
      format: "pdf",
      version: "1.0.0",
      structure: {
        slides: [
          {
            id: "title",
            layout: "title",
            content: "Value Analysis",
            style: {
              fontSize: 32,
              fontWeight: "bold",
              alignment: "center",
            },
          },
          {
            id: "executive_summary",
            layout: "content",
            content: "Executive Summary",
            style: {
              fontSize: 18,
              fontWeight: "bold",
            },
          },
          {
            id: "financial_impact",
            layout: "chart",
            content: "Financial Impact",
            style: {
              fontSize: 16,
            },
          },
          {
            id: "strategic_implications",
            layout: "content",
            content: "Strategic Implications",
            style: {
              fontSize: 16,
            },
          },
          {
            id: "recommendations",
            layout: "content",
            content: "Recommendations",
            style: {
              fontSize: 16,
            },
          },
          {
            id: "next_steps",
            layout: "content",
            content: "Next Steps",
            style: {
              fontSize: 16,
            },
          },
        ],
      },
      metadata: {
        description: "Board presentation deck",
        category: "governance",
        tags: ["board", "presentation", "strategic"],
        isDefault: true,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
  }

  /**
   * Get template by type
   */
  getTemplate(type: ArtifactType): ArtifactTemplate | undefined {
    return this.templates.get(type);
  }

  /**
   * List all templates
   */
  listTemplates(): ArtifactTemplate[] {
    return Array.from(this.templates.values());
  }

  /**
   * Register custom template
   */
  registerTemplate(template: ArtifactTemplate): void {
    this.templates.set(template.type, template);
  }

  // ============================================================================
  // PDF Generation
  // ============================================================================

  /**
   * Generate PDF from template
   */
  async generatePDF(
    content: PDFContent,
    options: PDFGenerationOptions = {}
  ): Promise<Blob> {
    try {
      // Get template
      let template: ArtifactTemplate | undefined;
      if (options.templateId) {
        template = Array.from(this.templates.values()).find(t => t.id === options.templateId);
      }

      if (!template && content.metadata?.type) {
        template = this.templates.get(content.metadata.type as ArtifactType);
      }

      // Apply branding
      const brandedContent = this.applyBranding(content, options.brandingProfile);

      // Generate PDF structure
      const pdfStructure = this.generatePDFStructure(brandedContent, template);

      // Create PDF blob (simulated - in real implementation, use jsPDF or similar)
      const pdfBlob = await this.createPDFBlob(pdfStructure, options);

      return pdfBlob;
    } catch (error) {
      throw new Error(`Failed to generate PDF: ${error instanceof Error ? error.message : "Unknown error"}`);
    }
  }

  /**
   * Apply branding to content
   */
  private applyBranding(content: PDFContent, brandingProfile?: BrandingProfile): PDFContent {
    if (!brandingProfile) {
      return content;
    }

    const brandedContent: PDFContent = {
      ...content,
      sections: content.sections.map(section => ({
        ...section,
        style: {
          ...section.style,
          color: section.style?.color || brandingProfile.primaryColor,
        },
      })),
      metadata: {
        ...content.metadata,
        branding: {
          logo: brandingProfile.logoUrl,
          primaryColor: brandingProfile.primaryColor,
          secondaryColor: brandingProfile.secondaryColor,
          accentColor: brandingProfile.accentColor,
          fontFamily: brandingProfile.fontFamily,
          companyName: brandingProfile.companyName,
          tagline: brandingProfile.tagline,
        },
      },
    };

    return brandedContent;
  }

  /**
   * Generate PDF structure
   */
  private generatePDFStructure(content: PDFContent, template?: ArtifactTemplate): any {
    const structure = {
      metadata: {
        title: content.title,
        author: content.metadata?.branding?.companyName || "ValueOS",
        creator: "ValueOS PDF Generator",
        created: new Date().toISOString(),
        branding: content.metadata?.branding,
      },
      sections: content.sections.map(section => ({
        ...section,
        style: {
          ...this.config.defaultMargins,
          fontSize: section.style?.fontSize || this.config.defaultFontSize,
          ...section.style,
        },
      })),
    };

    // Apply template structure if available
    if (template?.structure) {
      structure.sections = this.mergeWithTemplate(structure.sections, template.structure);
    }

    return structure;
  }

  /**
   * Merge content with template structure
   */
  private mergeWithTemplate(sections: any[], templateStructure: any): any[] {
    if (templateStructure.sections) {
      // Map template sections to content sections
      return templateStructure.sections.map((templateSection: any) => {
        const contentSection = sections.find(s => s.id === templateSection.id);
        return {
          ...templateSection,
          ...contentSection,
          style: {
            ...templateSection.style,
            ...contentSection?.style,
          },
        };
      });
    }

    if (templateStructure.slides) {
      return templateStructure.slides.map((templateSlide: any) => {
        const contentSection = sections.find(s => s.id === templateSlide.id);
        return {
          ...templateSlide,
          ...contentSection,
          style: {
            ...templateSlide.style,
            ...contentSection?.style,
          },
        };
      });
    }

    return sections;
  }

  /**
   * Create PDF blob (simulated)
   */
  private async createPDFBlob(structure: any, options: PDFGenerationOptions): Promise<Blob> {
    // In a real implementation, this would use jsPDF or similar library
    // For now, we'll create a simulated PDF blob with the structure as JSON
    const pdfContent = {
      version: "1.0",
      metadata: structure.metadata,
      sections: structure.sections,
      generatedAt: new Date().toISOString(),
      options: {
        compress: options.compress || false,
        quality: options.quality || "medium",
        includePageNumbers: options.includePageNumbers || false,
        includeTableOfContents: options.includeTableOfContents || false,
      },
    };

    const jsonStr = JSON.stringify(pdfContent, null, 2);
    return new Blob([jsonStr], { type: "application/pdf" });
  }

  // ============================================================================
  // Template Validation
  // ============================================================================

  /**
   * Validate template
   */
  validateTemplate(template: ArtifactTemplate): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!template.id) {
      errors.push("Template ID is required");
    }

    if (!template.name) {
      errors.push("Template name is required");
    }

    if (!template.type) {
      errors.push("Template type is required");
    }

    if (!template.format || template.format !== "pdf") {
      errors.push("Template format must be 'pdf'");
    }

    if (!template.structure) {
      errors.push("Template structure is required");
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  // ============================================================================
  // Branding Utilities
  // ============================================================================

  /**
   * Create branding profile
   */
  createBrandingProfile(profile: Omit<BrandingProfile, "id" | "createdAt" | "updatedAt">): BrandingProfile {
    return {
      id: crypto.randomUUID(),
      ...profile,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  }

  /**
   * Validate branding profile
   */
  validateBrandingProfile(profile: BrandingProfile): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!profile.primaryColor.match(/^#[0-9A-Fa-f]{6}$/)) {
      errors.push("Primary color must be a valid hex color");
    }

    if (!profile.secondaryColor.match(/^#[0-9A-Fa-f]{6}$/)) {
      errors.push("Secondary color must be a valid hex color");
    }

    if (!profile.accentColor.match(/^#[0-9A-Fa-f]{6}$/)) {
      errors.push("Accent color must be a valid hex color");
    }

    if (!profile.logoUrl.match(/^https?:\/\/.+/)) {
      errors.push("Logo URL must be a valid URL");
    }

    if (!profile.companyName) {
      errors.push("Company name is required");
    }

    if (!profile.fontFamily) {
      errors.push("Font family is required");
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  // ============================================================================
  // Content Utilities
  // ============================================================================

  /**
   * Create PDF content from value case
   */
  createContentFromValueCase(
    valueCase: any,
    templateType: ArtifactType,
    brandingProfile?: BrandingProfile
  ): PDFContent {
    const template = this.getTemplate(templateType);
    if (!template) {
      throw new Error(`Template not found for type: ${templateType}`);
    }

    const content: PDFContent = {
      title: `${template.name} - ${valueCase.companyName}`,
      sections: [],
      metadata: {
        type: templateType,
        valueCaseId: valueCase.id,
        companyName: valueCase.companyName,
        generatedAt: new Date().toISOString(),
      },
    };

    // Populate sections based on template type
    switch (templateType) {
      case "executive_summary":
        content.sections = this.createExecutiveSummarySections(valueCase);
        break;
      case "cfo_brief":
        content.sections = this.createCFOBriefSections(valueCase);
        break;
      case "board_deck":
        content.sections = this.createBoardDeckSections(valueCase);
        break;
      default:
        content.sections = this.createDefaultSections(valueCase);
    }

    // Apply branding
    if (brandingProfile) {
      content.metadata.branding = {
        logo: brandingProfile.logoUrl,
        primaryColor: brandingProfile.primaryColor,
        secondaryColor: brandingProfile.secondaryColor,
        accentColor: brandingProfile.accentColor,
        fontFamily: brandingProfile.fontFamily,
        companyName: brandingProfile.companyName,
        tagline: brandingProfile.tagline,
      };
    }

    return content;
  }

  /**
   * Create executive summary sections
   */
  private createExecutiveSummarySections(valueCase: any): PDFSection[] {
    return [
      {
        id: "header",
        type: "title",
        content: "Executive Summary",
        style: {
          fontSize: 24,
          fontWeight: "bold",
          alignment: "center",
        },
      },
      {
        id: "overview",
        type: "text",
        title: "Overview",
        content: valueCase.business_case?.overview || "No overview available",
        style: {
          fontSize: 12,
        },
      },
      {
        id: "key_metrics",
        type: "table",
        title: "Key Performance Indicators",
        content: valueCase.business_case?.metrics || [],
        style: {
          fontSize: 11,
        },
      },
      {
        id: "recommendations",
        type: "list",
        title: "Recommendations",
        content: valueCase.business_case?.recommendations || [],
        style: {
          fontSize: 12,
        },
      },
    ];
  }

  /**
   * Create CFO brief sections
   */
  private createCFOBriefSections(valueCase: any): PDFSection[] {
    return [
      {
        id: "header",
        type: "title",
        content: "ROI Analysis",
        style: {
          fontSize: 24,
          fontWeight: "bold",
          alignment: "center",
        },
      },
      {
        id: "financials",
        type: "table",
        title: "Financial Projections",
        content: valueCase.business_case?.financials || [],
        style: {
          fontSize: 11,
        },
      },
      {
        id: "risk_analysis",
        type: "text",
        title: "Risk Analysis",
        content: valueCase.business_case?.risk_analysis || "No risk analysis available",
        style: {
          fontSize: 12,
        },
      },
      {
        id: "payback_period",
        type: "table",
        title: "Payback Period",
        content: valueCase.business_case?.payback_period || [],
        style: {
          fontSize: 11,
        },
      },
      {
        id: "assumptions",
        type: "list",
        title: "Key Assumptions",
        content: valueCase.business_case?.assumptions || [],
        style: {
          fontSize: 12,
        },
      },
    ];
  }

  /**
   * Create board deck sections
   */
  private createBoardDeckSections(valueCase: any): PDFSection[] {
    return [
      {
        id: "title",
        type: "title",
        content: "Value Analysis",
        style: {
          fontSize: 32,
          fontWeight: "bold",
          alignment: "center",
        },
      },
      {
        id: "executive_summary",
        type: "text",
        title: "Executive Summary",
        content: valueCase.business_case?.overview || "No overview available",
        style: {
          fontSize: 18,
          fontWeight: "bold",
        },
      },
      {
        id: "financial_impact",
        type: "chart",
        title: "Financial Impact",
        content: valueCase.business_case?.financials || [],
        style: {
          fontSize: 16,
        },
      },
      {
        id: "strategic_implications",
        type: "text",
        title: "Strategic Implications",
        content: valueCase.business_case?.strategic_implications || "No strategic implications available",
        style: {
          fontSize: 16,
        },
      },
      {
        id: "recommendations",
        type: "list",
        title: "Recommendations",
        content: valueCase.business_case?.recommendations || [],
        style: {
          fontSize: 16,
        },
      },
      {
        id: "next_steps",
        type: "list",
        title: "Next Steps",
        content: valueCase.business_case?.next_steps || [],
        style: {
          fontSize: 16,
        },
      },
    ];
  }

  /**
   * Create default sections
   */
  private createDefaultSections(valueCase: any): PDFSection[] {
    return [
      {
        id: "header",
        type: "title",
        content: valueCase.companyName,
        style: {
          fontSize: 24,
          fontWeight: "bold",
          alignment: "center",
        },
      },
      {
        id: "content",
        type: "text",
        title: "Business Case",
        content: JSON.stringify(valueCase.business_case, null, 2),
        style: {
          fontSize: 12,
        },
      },
    ];
  }
}

// ============================================================================
// Singleton Instance
// ============================================================================

let pdfTemplateServiceInstance: PDFTemplateService | null = null;

export function getPDFTemplateService(config?: Partial<PDFTemplateConfig>): PDFTemplateService {
  if (!pdfTemplateServiceInstance) {
    pdfTemplateServiceInstance = new PDFTemplateService(config);
  }
  return pdfTemplateServiceInstance;
}

export function resetPDFTemplateService(): void {
  pdfTemplateServiceInstance = null;
}

// Default export
export default PDFTemplateService;
