#!/usr/bin/env bash
set -euo pipefail

# Ensure a project-level .env exists so `docker compose` interpolation succeeds.
# Usage: bash .devcontainer/scripts/ensure-dotenv.sh
#
# Source priority:
#   1. ops/env/.env.local  — generated by generate-env-from-secrets.sh from
#                            Ona-injected project secrets, or written manually.
#   2. Abort with a clear message if the source is missing (do not silently
#      fall back to a template that leaves secrets blank).

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SRC="$ROOT/ops/env/.env.local"
DEST="$ROOT/.env"

if [[ -f "$DEST" ]]; then
  echo "[ensure-dotenv] .env already exists at $DEST — no changes made."
  exit 0
fi

if [[ -f "$SRC" ]]; then
  cp "$SRC" "$DEST"
  chmod 600 "$DEST" 2>/dev/null || true
  echo "[ensure-dotenv] Created $DEST from ops/env/.env.local"
  exit 0
fi

echo "[ensure-dotenv] ERROR: ops/env/.env.local not found." >&2
echo "[ensure-dotenv] Run bootstrap.sh to generate it from Ona-injected secrets," >&2
echo "[ensure-dotenv] or create it manually from ops/env/.env.local.example." >&2
exit 1
