#!/usr/bin/env bash
# generate-env-from-secrets.sh
#
# Writes ops/env/.env.local by merging Ona-injected environment variables
# with the defaults declared in ops/env/.env.base.
#
# For each KEY=default in .env.base:
#   - If KEY is set (non-empty) in the current environment, use that value.
#   - Otherwise, keep the default from .env.base.
#
# Idempotent: skips generation if ops/env/.env.local already exists.
# Pass --force to overwrite an existing file.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
BASE="${ROOT}/ops/env/.env.base"
DEST="${ROOT}/ops/env/.env.local"

log()  { printf '[gen-env] %s\n' "$*"; }
warn() { printf '[gen-env] WARN: %s\n' "$*" >&2; }
die()  { printf '[gen-env] ERROR: %s\n' "$*" >&2; exit 1; }

FORCE=false
for arg in "$@"; do
  [[ "$arg" == "--force" ]] && FORCE=true
done

[[ -f "$BASE" ]] || die "ops/env/.env.base not found at $BASE"

if [[ -f "$DEST" ]] && [[ "$FORCE" == false ]]; then
  log "ops/env/.env.local already exists — skipping (pass --force to overwrite)"
  exit 0
fi

log "Generating $DEST from injected secrets + $BASE defaults..."

{
  printf '# Generated by generate-env-from-secrets.sh\n'
  printf '# Source: Ona project secrets (injected env) merged with ops/env/.env.base defaults.\n'
  printf '# Do not edit manually — re-run bootstrap to regenerate.\n'
  printf '\n'

  while IFS= read -r line || [[ -n "$line" ]]; do
    # Pass through blank lines and comments unchanged
    if [[ -z "$line" ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
      printf '%s\n' "$line"
      continue
    fi

    # Strip leading "export " if present
    line="${line#export }"

    # Only process KEY=value lines
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*) ]]; then
      key="${BASH_REMATCH[1]}"
      default="${BASH_REMATCH[2]}"

      # Prefer the live injected value; fall back to the .env.base default
      if [[ -n "${!key+set}" ]] && [[ -n "${!key}" ]]; then
        value="${!key}"
        printf '%s=%s\n' "$key" "$value"
      else
        printf '%s=%s\n' "$key" "$default"
      fi
    else
      printf '%s\n' "$line"
    fi
  done < "$BASE"
} > "$DEST"

chmod 600 "$DEST"
log "Written: $DEST"
