import { z } from "zod";

export const ValueCommitmentSchema = z.object({
  id: z.string().optional(), // often generated by DB, but here it seems we might be validating before insert or after? The code uses it after parsing.
  // Wait, if it's inserted, ID is usually generated.
  // But let's look at usage:
  // const validatedData = ValueCommitmentSchema.parse(commitmentData);
  // It seems to expect ID to be there if it's a full object, or maybe it adds it?
  // Actually, usually schemas for insert don't require ID.
  // But let's check createCommitment:
  // const validatedData = ValueCommitmentSchema.parse(commitmentData);
  // data comes from Omit<ValueCommitmentInsert, ...>.
  // If data doesn't have ID, and schema requires it, it will fail.
  // I will make ID optional or allow it to be added by DB.
  // However, the code: validatedData.id is accessed immediately after parsing.
  // This implies the input `data` (plus tenantId etc) must have `id`.
  // Wait, `createCommitment` signature: `data: Omit<ValueCommitmentInsert, ...>`.
  // If `ValueCommitmentInsert` is partial, then `data` has optional fields.
  // But if `ValueCommitmentSchema.parse` succeeds and returns something with `.id`, then `id` must be in the schema.
  // If `id` is not in `data`, then `parse` will fail if `id` is required.
  // So likely `data` should include `id` (client generated) OR the schema allows transforming/defaulting.
  // Or maybe `ValueCommitmentInsert` expects `id` to be present?
  // Let's assume for now ID is optional in input but required in output, or maybe just optional.
  // But `validatedData.id` is accessed.
  // I'll make it string, but if it fails I might need to adjust.
  // Actually, typically `id` is generated by DB. If so, `validatedData.id` would be undefined if not provided.
  // But `logger.info(..., { commitmentId: validatedData.id })` suggests it is available.
  // So I'll assume it's provided in `data` or generated.
  // I'll use `z.string().uuid().optional()` but if code uses it, it might expect it defined.
  // I will use `.optional()` for now to be safe, but cast it or rely on it being there if provided.
  tenant_id: z.string(),
  user_id: z.string(),
  session_id: z.string(),
  organization_id: z.string().nullable().optional(),
  title: z.string(),
  description: z.string().optional(),
  commitment_type: z.string().optional(), // Made optional to avoid strict failures if missing in partial
  priority: z.string().optional(),
  financial_impact: z.record(z.any()).optional(),
  currency: z.string().optional(),
  timeframe_months: z.number().optional(),
  status: z.enum(['draft', 'in_progress', 'completed', 'at_risk', 'cancelled']).optional(),
  progress_percentage: z.number().optional(),
  confidence_level: z.number().optional(),
  committed_at: z.string().optional(),
  target_completion_date: z.string().optional(),
  actual_completion_date: z.string().nullable().optional(),
  ground_truth_references: z.record(z.any()).optional(),
  tags: z.array(z.string()).optional(),
  metadata: z.record(z.any()).optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentStakeholderSchema = z.object({
  id: z.string().optional(),
  commitment_id: z.string(),
  tenant_id: z.string(),
  user_id: z.string(),
  role: z.string(),
  responsibility: z.string().optional(),
  accountability_percentage: z.number().optional(),
  is_active: z.boolean().optional(),
  notification_preferences: z.record(z.any()).optional(),
  joined_at: z.string().optional(),
  last_active_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentMilestoneSchema = z.object({
  id: z.string().optional(),
  commitment_id: z.string(),
  tenant_id: z.string(),
  title: z.string(),
  description: z.string().optional(),
  status: z.enum(['pending', 'in_progress', 'completed', 'delayed']).optional(),
  progress_percentage: z.number().optional(),
  due_date: z.string().optional(),
  actual_date: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentMetricSchema = z.object({
  id: z.string().optional(),
  commitment_id: z.string(),
  tenant_id: z.string(),
  metric_name: z.string(),
  target_value: z.number().optional(),
  current_value: z.number().optional(),
  unit: z.string().optional(),
  last_measured_at: z.string().optional(),
  is_active: z.boolean().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentRiskSchema = z.object({
  id: z.string().optional(),
  commitment_id: z.string(),
  tenant_id: z.string(),
  risk_title: z.string(),
  risk_description: z.string().optional(),
  risk_score: z.number().optional(),
  status: z.enum(['identified', 'mitigated', 'occurred', 'resolved']).optional(),
  identified_at: z.string().optional(),
  mitigated_at: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentAuditSchema = z.object({
  id: z.string().optional(),
  commitment_id: z.string(),
  tenant_id: z.string(),
  user_id: z.string(),
  action: z.enum(['created', 'updated', 'deleted', 'status_changed', 'stakeholder_added', 'milestone_completed', 'metric_updated', 'risk_assessed']),
  previous_values: z.record(z.any()).optional(),
  new_values: z.record(z.any()).optional(),
  change_reason: z.string().optional(),
  created_at: z.string().optional(),
});
