import { z } from "zod";

export const ValueCommitmentSchema = z.object({
  id: z.string().uuid().optional(),
  tenant_id: z.string().uuid(),
  session_id: z.string().uuid(),
  user_id: z.string().uuid(),
  organization_id: z.string().uuid().nullable().optional(),
  title: z.string().min(1).max(200),
  description: z.string().min(1).max(2000),
  commitment_type: z.enum(['financial', 'timeline', 'operational', 'strategic', 'compliance']),
  priority: z.enum(['critical', 'high', 'medium', 'low']).default('medium'),
  financial_impact: z.record(z.any()).default({}),
  currency: z.string().default('USD'),
  timeframe_months: z.number().int().min(1).max(120),
  status: z.enum(['draft', 'committed', 'in_progress', 'on_track', 'at_risk', 'completed', 'cancelled', 'failed']).default('draft'),
  progress_percentage: z.number().min(0).max(100).default(0),
  confidence_level: z.number().min(0).max(100).default(50),
  committed_at: z.string().datetime().default(() => new Date().toISOString()),
  target_completion_date: z.string().datetime(),
  actual_completion_date: z.string().datetime().nullable().optional(),
  ground_truth_references: z.record(z.any()).default({}),
  tags: z.array(z.string()).default([]),
  metadata: z.record(z.any()).default({}),
});

export const CommitmentStakeholderSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  user_id: z.string().uuid(),
  role: z.enum(['owner', 'contributor', 'approver', 'reviewer', 'observer']),
  responsibility: z.string().min(1).max(500),
  accountability_percentage: z.number().min(0).max(100).default(50),
  notification_preferences: z.record(z.any()).default({}),
  joined_at: z.string().datetime().default(() => new Date().toISOString()),
  last_active_at: z.string().datetime().default(() => new Date().toISOString()),
  is_active: z.boolean().default(true),
});

export const CommitmentMilestoneSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  title: z.string().min(1).max(200),
  description: z.string().min(1).max(1000),
  milestone_type: z.enum(['planning', 'execution', 'review', 'completion', 'validation']),
  sequence_order: z.number().int().min(1),
  target_date: z.string().datetime(),
  actual_date: z.string().datetime().nullable().optional(),
  status: z.enum(['pending', 'in_progress', 'completed', 'delayed', 'cancelled']).default('pending'),
  progress_percentage: z.number().min(0).max(100).default(0),
  deliverables: z.array(z.string()).default([]),
  dependencies: z.array(z.string()).default([]),
  assigned_to: z.string().uuid().nullable().optional(),
  success_criteria: z.array(z.string()).default([]),
  metadata: z.record(z.any()).default({}),
});

export const CommitmentMetricSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  metric_name: z.string().min(1).max(100),
  metric_description: z.string().min(1).max(500),
  metric_type: z.enum(['kpi', 'roi', 'progress', 'quality', 'efficiency']),
  target_value: z.number(),
  current_value: z.number().nullable().optional(),
  unit: z.string().min(1).max(20),
  measurement_frequency: z.enum(['daily', 'weekly', 'monthly', 'quarterly', 'annually']).default('monthly'),
  baseline_value: z.number().nullable().optional(),
  tolerance_percentage: z.number().min(0).max(100).default(10),
  last_measured_at: z.string().datetime().nullable().optional(),
  next_measurement_date: z.string().datetime(),
  data_source: z.string().min(1).max(200),
  is_active: z.boolean().default(true),
  metadata: z.record(z.any()).default({}),
});

export const CommitmentAuditSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  user_id: z.string().uuid(),
  action: z.enum(['created', 'updated', 'status_changed', 'stakeholder_added', 'stakeholder_removed', 'milestone_completed', 'metric_updated', 'risk_assessed']),
  previous_values: z.record(z.any()).default({}),
  new_values: z.record(z.any()).default({}),
  change_reason: z.string().min(1).max(500),
  ip_address: z.string().nullable().optional(),
  user_agent: z.string().nullable().optional(),
  audit_metadata: z.record(z.any()).default({}),
});

export const CommitmentRiskSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  risk_title: z.string().min(1).max(200),
  risk_description: z.string().min(1).max(1000),
  risk_category: z.enum(['execution', 'resource', 'market', 'technical', 'regulatory', 'financial']),
  probability: z.enum(['low', 'medium', 'high', 'critical']),
  impact: z.enum(['low', 'medium', 'high', 'critical']),
  risk_score: z.number().nullable().optional(),
  mitigation_plan: z.string().min(1).max(2000),
  contingency_plan: z.string().min(1).max(2000),
  owner_id: z.string().uuid(),
  status: z.enum(['identified', 'mitigating', 'mitigated', 'occurred', 'closed']).default('identified'),
  identified_at: z.string().datetime().default(() => new Date().toISOString()),
  mitigated_at: z.string().datetime().nullable().optional(),
  occurred_at: z.string().datetime().nullable().optional(),
  review_date: z.string().datetime(),
  metadata: z.record(z.any()).default({}),
});
