import { z } from "zod";

export const ValueCommitmentSchema = z.object({
  id: z.string().uuid().optional(),
  tenant_id: z.string(),
  session_id: z.string().optional(),
  user_id: z.string(),
  organization_id: z.string().nullable().optional(),
  title: z.string().min(1),
  description: z.string().optional(),
  commitment_type: z.enum(['financial', 'timeline', 'operational', 'strategic', 'compliance']),
  priority: z.enum(['low', 'medium', 'high', 'critical']),
  financial_impact: z.record(z.any()).optional(),
  currency: z.string().optional(),
  timeframe_months: z.number().optional(),
  status: z.enum(['draft', 'committed', 'in_progress', 'on_track', 'at_risk', 'completed', 'cancelled', 'failed']),
  progress_percentage: z.number().min(0).max(100),
  confidence_level: z.number().min(0).max(100).optional(),
  committed_at: z.string().optional(),
  target_completion_date: z.string().optional(),
  actual_completion_date: z.string().nullable().optional(),
  ground_truth_references: z.record(z.any()).optional(),
  tags: z.array(z.string()).optional(),
  metadata: z.record(z.any()).optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentStakeholderSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string(),
  user_id: z.string(),
  role: z.enum(['owner', 'contributor', 'approver', 'reviewer', 'observer']),
  responsibility: z.string().optional(),
  accountability_percentage: z.number().min(0).max(100).optional(),
  is_active: z.boolean().default(true),
  notification_preferences: z.record(z.boolean()).optional(),
  joined_at: z.string().optional(),
  last_active_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentMilestoneSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string(),
  title: z.string().min(1),
  description: z.string().optional(),
  milestone_type: z.string().optional(),
  sequence_order: z.number().optional(),
  target_date: z.string().optional(),
  actual_date: z.string().optional(),
  progress_percentage: z.number().min(0).max(100).default(0),
  status: z.enum(['pending', 'in_progress', 'completed', 'delayed', 'skipped']).default('pending'),
  deliverables: z.array(z.string()).optional(),
  success_criteria: z.array(z.string()).optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentMetricSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string(),
  metric_name: z.string().min(1),
  metric_description: z.string().optional(),
  metric_type: z.enum(['kpi', 'leading_indicator', 'lagging_indicator']).optional(),
  current_value: z.number().optional(),
  target_value: z.number().optional(),
  unit: z.string().optional(),
  measurement_frequency: z.string().optional(),
  baseline_value: z.number().optional(),
  tolerance_percentage: z.number().optional(),
  data_source: z.string().optional(),
  last_measured_at: z.string().optional(),
  next_measurement_date: z.string().optional(),
  is_active: z.boolean().default(true),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentRiskSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string(),
  risk_title: z.string().min(1),
  risk_description: z.string().optional(),
  risk_category: z.string().optional(),
  probability: z.number().min(1).max(4).optional(),
  impact: z.number().min(1).max(4).optional(),
  risk_score: z.number().optional(),
  status: z.enum(['identified', 'analyzed', 'mitigated', 'occurred', 'closed']).default('identified'),
  mitigation_plan: z.string().optional(),
  owner_id: z.string().optional(),
  identified_at: z.string().optional(),
  mitigated_at: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const CommitmentAuditSchema = z.object({
  id: z.string().uuid().optional(),
  commitment_id: z.string().uuid(),
  tenant_id: z.string(),
  user_id: z.string(),
  action: z.string().min(1),
  previous_values: z.record(z.any()).optional(),
  new_values: z.record(z.any()).optional(),
  change_reason: z.string().optional(),
  created_at: z.string().optional(),
});
