#!/usr/bin/env node

/**
 * Environment Generator
 * Interactive environment file generation with secure defaults
 *
 * DEPRECATION NOTICE:
 * The writeEnvFile() function in this module is deprecated.
 * Use scripts/dx/env-compiler.js as the single source of truth for env generation.
 *
 * This module still provides:
 * - generateSecrets() - for generating secure random values
 * - setupEnvironment() - for interactive setup (delegates to env-compiler)
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Generate cryptographically secure random string
 */
function generateSecret(bytes = 32) {
  return crypto.randomBytes(bytes).toString('hex');
}

/**
 * Generate secure secrets
 */
export function generateSecrets() {
  return {
    JWT_SECRET: generateSecret(32),
    SUPABASE_JWT_SECRET: generateSecret(32),
    SESSION_SECRET: generateSecret(32),
    ENCRYPTION_KEY: generateSecret(32),
    DATABASE_PASSWORD: generateSecret(16),
    REDIS_PASSWORD: generateSecret(16)
  };
}

/**
 * Read .env.example template
 */
function readEnvTemplate() {
  const projectRoot = path.resolve(__dirname, '../..');
  const templatePath = path.join(projectRoot, '.env.example');
  
  if (!fs.existsSync(templatePath)) {
    console.log('⚠️  .env.example not found, creating minimal template');
    return `# ValueOS Environment Configuration
# Generated by setup script

NODE_ENV=development

# Database
DATABASE_URL=postgresql://postgres:postgres@localhost:54322/postgres
VITE_SUPABASE_URL=http://localhost:54321
VITE_SUPABASE_ANON_KEY=

# Secrets (auto-generated)
JWT_SECRET=
SUPABASE_JWT_SECRET=
SESSION_SECRET=

# Redis
REDIS_URL=redis://localhost:6379

# Frontend
VITE_APP_URL=http://localhost:5173

# Backend
BACKEND_URL=http://localhost:3000
PORT=3000
`;
  }

  return fs.readFileSync(templatePath, 'utf8');
}

/**
 * Parse environment template
 */
function parseEnvTemplate(template) {
  const lines = template.split('\n');
  const vars = {};
  
  lines.forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key) {
        vars[key.trim()] = valueParts.join('=').trim();
      }
    }
  });
  
  return vars;
}

/**
 * Prompt for user input (simplified for non-interactive environments)
 */
async function prompt(question, defaultValue = '') {
  // In a real implementation, use inquirer or readline
  // For now, return defaults
  return defaultValue;
}

/**
 * Generate environment configuration
 */
export async function generateEnvironment(options = {}) {
  console.log('\n🎯 Generating environment configuration...\n');

  // Read template
  const template = readEnvTemplate();
  const templateVars = parseEnvTemplate(template);

  // Generate secure secrets
  const secrets = generateSecrets();

  // Get user preferences (or use defaults)
  const projectName = options.projectName || 'valueos-dev';
  const environment = options.environment || 'development';
  const enableDebug = options.enableDebug !== false;

  // Build environment configuration
  const env = {
    ...templateVars,
    NODE_ENV: environment,
    
    // Database
    DATABASE_URL: `postgresql://postgres:${secrets.DATABASE_PASSWORD}@localhost:54322/postgres`,
    VITE_SUPABASE_URL: 'http://localhost:54321',
    
    // Secrets
    JWT_SECRET: secrets.JWT_SECRET,
    SUPABASE_JWT_SECRET: secrets.SUPABASE_JWT_SECRET,
    SESSION_SECRET: secrets.SESSION_SECRET,
    
    // Redis
    REDIS_URL: `redis://localhost:6379`,
    
    // Frontend
    VITE_APP_URL: 'http://localhost:5173',
    
    // Backend
    BACKEND_URL: 'http://localhost:3000',
    PORT: '3000',
    
    // Debug
    DEBUG: enableDebug ? 'valueos:*' : '',
    LOG_LEVEL: enableDebug ? 'debug' : 'info'
  };

  return env;
}

/**
 * Write environment file
 *
 * @deprecated Use scripts/dx/env-compiler.js instead.
 * This function is kept for backwards compatibility but will be removed.
 * The env-compiler provides mode-aware URL generation and validation.
 */
export function writeEnvFile(env, filename = '.env') {
  console.warn('⚠️  writeEnvFile() is deprecated. Use: npm run dx:env --mode local');
  
  const projectRoot = path.resolve(__dirname, '../..');
  const envPath = path.join(projectRoot, filename);

  // Build file content
  let content = '# ValueOS Environment Configuration\n';
  content += `# Generated: ${new Date().toISOString()}\n`;
  content += '# WARNING: Generated by deprecated writeEnvFile()\n';
  content += '# Use "npm run dx:env" for proper mode-aware generation\n\n';

  // Group variables by category
  const categories = {
    'Environment': ['NODE_ENV', 'DEBUG', 'LOG_LEVEL'],
    'Database': ['DATABASE_URL', 'VITE_SUPABASE_URL', 'VITE_SUPABASE_ANON_KEY'],
    'Secrets': ['JWT_SECRET', 'SUPABASE_JWT_SECRET', 'SESSION_SECRET', 'ENCRYPTION_KEY'],
    'Redis': ['REDIS_URL', 'REDIS_PASSWORD'],
    'Frontend': ['VITE_APP_URL'],
    'Backend': ['BACKEND_URL', 'PORT']
  };

  Object.entries(categories).forEach(([category, keys]) => {
    content += `# ${category}\n`;
    keys.forEach(key => {
      if (env[key] !== undefined) {
        content += `${key}=${env[key]}\n`;
      }
    });
    content += '\n';
  });

  // Add remaining variables
  const categorizedKeys = new Set(Object.values(categories).flat());
  const remainingKeys = Object.keys(env).filter(k => !categorizedKeys.has(k));
  
  if (remainingKeys.length > 0) {
    content += '# Other\n';
    remainingKeys.forEach(key => {
      content += `${key}=${env[key]}\n`;
    });
  }

  fs.writeFileSync(envPath, content, 'utf8');
  console.log(`✅ Created ${filename}`);
  
  return envPath;
}

/**
 * Validate environment configuration
 */
export function validateEnv(env) {
  const required = [
    'NODE_ENV',
    'DATABASE_URL',
    'JWT_SECRET'
  ];

  const missing = required.filter(key => !env[key] || env[key].trim() === '');

  if (missing.length > 0) {
    console.log('❌ Missing required environment variables:');
    missing.forEach(key => console.log(`   - ${key}`));
    return false;
  }

  // Check for weak secrets
  const weakSecrets = ['secret', 'password', '123', 'test', 'changeme'];
  const secretKeys = ['JWT_SECRET', 'SESSION_SECRET', 'SUPABASE_JWT_SECRET'];
  
  for (const key of secretKeys) {
    if (env[key]) {
      const value = env[key].toLowerCase();
      if (weakSecrets.some(weak => value.includes(weak)) || value.length < 32) {
        console.log(`⚠️  Weak secret detected for ${key}`);
        console.log('   Run: npm run setup to generate secure secrets');
        return false;
      }
    }
  }

  console.log('✅ Environment configuration valid');
  return true;
}

/**
 * Main setup function
 */
export async function setupEnvironment(options = {}) {
  try {
    // Generate configuration
    const env = await generateEnvironment(options);

    // Write to file
    const envFile = options.envFile || '.env.local';
    const envPath = writeEnvFile(env, envFile);
    
    // Validate
    const valid = validateEnv(env);
    
    if (!valid) {
      throw new Error('Environment validation failed');
    }

    console.log('\n✅ Environment setup complete!\n');
    console.log('Next steps:');
    console.log(`  1. Review ${envFile} file`);
    console.log('  2. Run: npm install');
    console.log('  3. Run: npm run dx\n');

    return { env, envPath, valid };
  } catch (error) {
    console.error('❌ Environment setup failed:', error.message);
    throw error;
  }
}

// CLI usage
if (import.meta.url === `file://${process.argv[1]}`) {
  setupEnvironment().catch(error => {
    process.exit(1);
  });
}
