/**
 * Mermaid Codemap Generator
 *
 * Generates Mermaid diagrams from dependency analysis
 * for visual representation in GitHub PR comments
 */

import * as fs from "fs";
import * as path from "path";

interface ImpactAnalysis {
  changedFiles: string[];
  directDependencies: string[];
  affectedFiles: string[];
  blastRadius: number;
  riskScore: number;
  affectedTests: string[];
  affectedServices: string[];
}

/**
 * Generate Mermaid diagram from impact analysis
 */
export function generateMermaidDiagram(impact: ImpactAnalysis): string {
  const changedFiles = impact.changedFiles.slice(0, 5); // Limit to 5 for readability
  const affectedFiles = impact.affectedFiles.slice(0, 10);

  let diagram = "graph TD\n";

  // Add changed files (red nodes)
  for (let i = 0; i < changedFiles.length; i++) {
    const file = changedFiles[i];
    const nodeId = `changed${i}`;
    const fileName = getFileName(file);
    diagram += `  ${nodeId}["${fileName}"]:::changed\n`;
  }

  // Add affected files (yellow nodes)
  for (let i = 0; i < affectedFiles.length; i++) {
    const file = affectedFiles[i];
    const nodeId = `affected${i}`;
    const fileName = getFileName(file);
    diagram += `  ${nodeId}["${fileName}"]:::affected\n`;

    // Add edge from changed to affected
    const changedIdx = i % changedFiles.length;
    diagram += `  changed${changedIdx} --> ${nodeId}\n`;
  }

  // Add service nodes (blue nodes)
  for (const service of impact.affectedServices) {
    const serviceId = service.replace(/\s+/g, "");
    diagram += `  ${serviceId}[["${service}"]]:::service\n`;

    // Connect to affected files
    const affectedIdx = Math.floor(
      Math.random() * Math.min(affectedFiles.length, 3)
    );
    diagram += `  affected${affectedIdx} -.-> ${serviceId}\n`;
  }

  // Add styles
  diagram += "\n";
  diagram += "  classDef changed fill:#ff6b6b,stroke:#c92a2a,color:#fff\n";
  diagram += "  classDef affected fill:#ffd43b,stroke:#f59f00,color:#000\n";
  diagram += "  classDef service fill:#4dabf7,stroke:#1c7ed6,color:#fff\n";

  return diagram;
}

/**
 * Generate risk badge
 */
export function generateRiskBadge(riskScore: number): string {
  if (riskScore >= 8) {
    return "🔴 **HIGH RISK**";
  } else if (riskScore >= 5) {
    return "🟡 **MEDIUM RISK**";
  } else {
    return "🟢 **LOW RISK**";
  }
}

/**
 * Generate full PR comment markdown
 */
export function generatePRComment(impact: ImpactAnalysis): string {
  const riskBadge = generateRiskBadge(impact.riskScore);
  const diagram = generateMermaidDiagram(impact);

  let comment = `## 🗺️ Architectural Codemap\n\n`;

  // Risk score
  comment += `### Risk Assessment\n\n`;
  comment += `${riskBadge} - Risk Score: **${impact.riskScore}/10**\n\n`;

  // Mermaid diagram
  comment += `### Dependency Graph\n\n`;
  comment += `\`\`\`mermaid\n${diagram}\`\`\`\n\n`;

  // Blast radius
  comment += `### Blast Radius\n\n`;
  comment += `| Metric | Count |\n`;
  comment += `|--------|-------|\n`;
  comment += `| Changed Files | ${impact.changedFiles.length} |\n`;
  comment += `| Affected Files | ${impact.affectedFiles.length} |\n`;
  comment += `| Affected Tests | ${impact.affectedTests.length} |\n`;
  comment += `| Affected Services | ${impact.affectedServices.length} |\n\n`;

  // Changed files
  if (impact.changedFiles.length > 0) {
    comment += `<details>\n`;
    comment += `<summary><strong>Changed Files (${impact.changedFiles.length})</strong></summary>\n\n`;
    for (const file of impact.changedFiles) {
      comment += `- \`${file}\`\n`;
    }
    comment += `\n</details>\n\n`;
  }

  // Affected services
  if (impact.affectedServices.length > 0) {
    comment += `### Affected Services\n\n`;
    for (const service of impact.affectedServices) {
      comment += `- 🏗️ **${service}**\n`;
    }
    comment += `\n`;
  }

  // Recommendations
  comment += `### Recommendations\n\n`;
  if (impact.riskScore >= 8) {
    comment += `- ⚠️ **High risk change** - Request additional review\n`;
    comment += `- 🧪 Run full integration test suite\n`;
    comment += `- 📊 Monitor metrics closely after deployment\n`;
  } else if (impact.riskScore >= 5) {
    comment += `- ✅ Run affected tests: \`pnpm test -- ${impact.affectedTests.slice(0, 3).join(" ")}\`\n`;
    comment += `- 📈 Review performance impact\n`;
  } else {
    comment += `- ✅ Low risk - Standard review process\n`;
  }

  comment += `\n---\n`;
  comment += `<sub>Generated by ValueOS Cognitive Pipeline | [Learn more](../../../docs/cognitive-pipeline.md)</sub>\n`;

  return comment;
}

/**
 * Get shortened file name
 */
function getFileName(filePath: string): string {
  const parts = filePath.split("/");
  if (parts.length > 2) {
    return `.../${parts.slice(-2).join("/")}`;
  }
  return path.basename(filePath);
}

// CLI execution
if (import.meta.url === `file://${process.argv[1]}`) {
  const impactPath = process.argv[2] || "impact.json";

  if (!fs.existsSync(impactPath)) {
    console.error(`❌ Impact analysis not found: ${impactPath}`);
    console.error("   Run: pnpm run analyze:deps first");
    process.exit(1);
  }

  const impact: ImpactAnalysis = JSON.parse(
    fs.readFileSync(impactPath, "utf-8")
  );
  const comment = generatePRComment(impact);

  fs.writeFileSync("pr-comment.md", comment);
  console.log("✅ Generated PR comment: pr-comment.md");
  console.log(comment);
}
