"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnknownComponentFallback = exports.NarrativeBlock = exports.ValueTreeCard = exports.InteractiveChart = exports.KPIForm = exports.DiscoveryCard = exports.ComponentPreview = exports.ProgressBar = exports.ValueHypothesisCard = exports.ConfirmationDialog = exports.TextBlock = exports.JsonViewer = exports.ValueCommitForm = exports.TabBar = exports.SideNavigation = exports.SectionErrorFallback = exports.SDUIForm = exports.ScenarioSelector = exports.RealizationDashboard = exports.MetricBadge = exports.LifecyclePanel = exports.IntegrityReviewPanel = exports.InfoBanner = exports.ExpansionBlock = exports.DataTable = exports.ConfidenceIndicator = exports.Breadcrumbs = exports.AgentWorkflowPanel = exports.AgentResponseCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = require("react");
const lucide_react_1 = require("lucide-react");
// Placeholder components - these need to be implemented
const AgentResponseCard = () => ((0, jsx_runtime_1.jsx)("div", { children: "AgentResponseCard - Not implemented" }));
exports.AgentResponseCard = AgentResponseCard;
const AgentWorkflowPanel = () => ((0, jsx_runtime_1.jsx)("div", { children: "AgentWorkflowPanel - Not implemented" }));
exports.AgentWorkflowPanel = AgentWorkflowPanel;
const Breadcrumbs = () => (0, jsx_runtime_1.jsx)("div", { children: "Breadcrumbs - Not implemented" });
exports.Breadcrumbs = Breadcrumbs;
const ConfidenceIndicator = () => ((0, jsx_runtime_1.jsx)("div", { children: "ConfidenceIndicator - Not implemented" }));
exports.ConfidenceIndicator = ConfidenceIndicator;
const DataTable = () => (0, jsx_runtime_1.jsx)("div", { children: "DataTable - Not implemented" });
exports.DataTable = DataTable;
const ExpansionBlock = () => (0, jsx_runtime_1.jsx)("div", { children: "ExpansionBlock - Not implemented" });
exports.ExpansionBlock = ExpansionBlock;
const InfoBanner = () => (0, jsx_runtime_1.jsx)("div", { children: "InfoBanner - Not implemented" });
exports.InfoBanner = InfoBanner;
const IntegrityReviewPanel = () => ((0, jsx_runtime_1.jsx)("div", { children: "IntegrityReviewPanel - Not implemented" }));
exports.IntegrityReviewPanel = IntegrityReviewPanel;
const LifecyclePanel = () => (0, jsx_runtime_1.jsx)("div", { children: "LifecyclePanel - Not implemented" });
exports.LifecyclePanel = LifecyclePanel;
const MetricBadge = () => (0, jsx_runtime_1.jsx)("div", { children: "MetricBadge - Not implemented" });
exports.MetricBadge = MetricBadge;
const RealizationDashboard = () => ((0, jsx_runtime_1.jsx)("div", { children: "RealizationDashboard - Not implemented" }));
exports.RealizationDashboard = RealizationDashboard;
const ScenarioSelector = () => (0, jsx_runtime_1.jsx)("div", { children: "ScenarioSelector - Not implemented" });
exports.ScenarioSelector = ScenarioSelector;
const SDUIForm = () => (0, jsx_runtime_1.jsx)("div", { children: "SDUIForm - Not implemented" });
exports.SDUIForm = SDUIForm;
const SectionErrorFallback = () => ((0, jsx_runtime_1.jsx)("div", { children: "SectionErrorFallback - Not implemented" }));
exports.SectionErrorFallback = SectionErrorFallback;
const SideNavigation = () => (0, jsx_runtime_1.jsx)("div", { children: "SideNavigation - Not implemented" });
exports.SideNavigation = SideNavigation;
const TabBar = () => (0, jsx_runtime_1.jsx)("div", { children: "TabBar - Not implemented" });
exports.TabBar = TabBar;
const ValueCommitForm = () => (0, jsx_runtime_1.jsx)("div", { children: "ValueCommitForm - Not implemented" });
exports.ValueCommitForm = ValueCommitForm;
const JsonViewer = () => (0, jsx_runtime_1.jsx)("div", { children: "JsonViewer - Not implemented" });
exports.JsonViewer = JsonViewer;
const TextBlock = () => (0, jsx_runtime_1.jsx)("div", { children: "TextBlock - Not implemented" });
exports.TextBlock = TextBlock;
const ConfirmationDialog = () => ((0, jsx_runtime_1.jsx)("div", { children: "ConfirmationDialog - Not implemented" }));
exports.ConfirmationDialog = ConfirmationDialog;
const ValueHypothesisCard = () => ((0, jsx_runtime_1.jsx)("div", { children: "ValueHypothesisCard - Not implemented" }));
exports.ValueHypothesisCard = ValueHypothesisCard;
const ProgressBar = () => (0, jsx_runtime_1.jsx)("div", { children: "ProgressBar - Not implemented" });
exports.ProgressBar = ProgressBar;
const ComponentPreview = () => (0, jsx_runtime_1.jsx)("div", { children: "ComponentPreview - Not implemented" });
exports.ComponentPreview = ComponentPreview;
// Re-export implemented components from their own files
var DiscoveryCard_1 = require("./DiscoveryCard");
Object.defineProperty(exports, "DiscoveryCard", { enumerable: true, get: function () { return DiscoveryCard_1.DiscoveryCard; } });
var KPIForm_1 = require("./KPIForm");
Object.defineProperty(exports, "KPIForm", { enumerable: true, get: function () { return KPIForm_1.KPIForm; } });
var InteractiveChart_1 = require("./InteractiveChart");
Object.defineProperty(exports, "InteractiveChart", { enumerable: true, get: function () { return InteractiveChart_1.InteractiveChart; } });
var ValueTreeCard_1 = require("./ValueTreeCard");
Object.defineProperty(exports, "ValueTreeCard", { enumerable: true, get: function () { return ValueTreeCard_1.ValueTreeCard; } });
var NarrativeBlock_1 = require("./NarrativeBlock");
Object.defineProperty(exports, "NarrativeBlock", { enumerable: true, get: function () { return NarrativeBlock_1.NarrativeBlock; } });
const isDev = typeof process !== "undefined" && process.env?.NODE_ENV === "development";
const UnknownComponentFallback = ({ componentName = "Unknown", props, className = "", }) => {
    const [showProps, setShowProps] = (0, react_1.useState)(false);
    return ((0, jsx_runtime_1.jsxs)("div", { "data-testid": "unknown-component-fallback", className: `bg-card border border-border rounded-lg p-4 ${className}`, children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2 text-muted-foreground", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertTriangle, { className: "w-5 h-5 text-yellow-500 shrink-0" }), (0, jsx_runtime_1.jsxs)("span", { className: "text-sm font-medium", children: ["Unknown component: ", (0, jsx_runtime_1.jsx)("code", { className: "text-xs bg-secondary px-1.5 py-0.5 rounded", children: componentName })] })] }), isDev && props && Object.keys(props).length > 0 && ((0, jsx_runtime_1.jsxs)("div", { className: "mt-3", children: [(0, jsx_runtime_1.jsxs)("button", { onClick: () => setShowProps(!showProps), className: "flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors", children: [showProps ? (0, jsx_runtime_1.jsx)(lucide_react_1.ChevronDown, { className: "w-3 h-3" }) : (0, jsx_runtime_1.jsx)(lucide_react_1.ChevronRight, { className: "w-3 h-3" }), "Requested props"] }), showProps && ((0, jsx_runtime_1.jsx)("pre", { className: "mt-2 text-xs bg-secondary/50 rounded p-2 overflow-auto max-h-48 text-muted-foreground", children: JSON.stringify(props, null, 2) }))] }))] }));
};
exports.UnknownComponentFallback = UnknownComponentFallback;
exports.UnknownComponentFallback.displayName = "UnknownComponentFallback";
//# sourceMappingURL=index.js.map